### ISSUE TITLE
superadmin.p12 ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by Nobody0404** [Keyfactor/ejbca-ce#102]
Hi,

I installed ejbca following the officials documentation using wildfly 22 and ejbca 7.9.0.2 all worked fine except that in the end when i installaed the superadmin.p12 certificate on differents browser i got this message error

```
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

when using curl 
 ```
curl --tlsv1.2 --tls-max 1.2 -v --cert-type P12 --cert /tmp/superadmin.p12:ejbca https://localhost:8443/ejbca/adminweb/
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

thanks in advance.

**Comment by primetomas** [comment]
What kind of keys are you using on the server and superadmin? We've seen this when for example trying to use DSA instead of RSA or ECDSA.

**Comment by Nobody0404** [comment]
i used those command during installation

```
/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=elytron/server-ssl-context=httpspub:add(key-manager=httpsKM,protocols=["TLSv1.2"],use-cipher-suites-order=false,cipher-suite-filter="TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256")'
/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=elytron/server-ssl-context=httpspriv:add(key-manager=httpsKM,protocols=["TLSv1.2"],use-cipher-suites-order=false,cipher-suite-filter="TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",trust-manager=httpsTM,need-client-auth=true)'
```

is this what you asked for?

**Comment by primetomas** [comment]
One part sure. Here you only configure RSA based TLS cipher suites. This will not work if you then generate ECDSA TLS server keys or ECDSA superadmin keys (anything else than RSA keys will fail with your selected TLS cipher suites).

**Comment by Nobody0404** [comment]
what should i do to get it working? I just followed the documentation

**Comment by primetomas** [comment]
These instructions? 
https://doc.primekey.com/ejbca/ejbca-installation

With this? 
https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-22-jboss-eap-7-4

How about if you connect to https://localhost:8442/ejbca (no client certificate connection)

**Comment by primetomas** [comment]
Your setting above doesn't match what I copy and paste from there, there are many more cipher suites.

(looking at 3 port separation)

```
/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=elytron/server-ssl-context=httpspub:add(key-manager=httpsKM,protocols=["TLSv1.3","TLSv1.2"],use-cipher-suites-order=false,cipher-suite-filter="TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",cipher-suite-names="TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256")'
/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=elytron/server-ssl-context=httpspriv:add(key-manager=httpsKM,protocols=["TLSv1.3","TLSv1.2"],use-cipher-suites-order=false,cipher-suite-filter="TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",cipher-suite-names="TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256",trust-manager=httpsTM,need-client-auth=true)'
```

**Comment by Nobody0404** [comment]
Hi @primetomas thanks for your help, i redid the installation with the links you give( 3 port separation and i left everything at default value to make sure i didn't miss something but i am having the same problemes. I don't know what is the wrong step i did.

**Comment by primetomas** [comment]
That is very strange indeed. What browser are you using?

You can try a more packaged approach, which avoids any server specific confgiuration issues. If you start/try the docker container. Does that work for you?
https://hub.docker.com/r/keyfactor/ejbca-ce

**Comment by Nobody0404** [comment]
when using docker it worked perfectly
![image](https://user-images.githubusercontent.com/44438334/194321141-8c9c9406-5f56-4667-ad3a-62fb30c4eb86.png)

i have a question can i use docker installation in a production envirenement?
Thanks.

**Comment by primetomas** [comment]
Absolutely you can. Then you should use a configuration with external database, so you maintain your database outside of the EJBCA container. The data in the container is where the production important stuff lives. Then there is also HSMs for production, which you can read about on our GitHub repositories as well.

**Comment by Nobody0404** [comment]
thanks for your help
