### ISSUE TITLE
Refreshing Crypto Tokens page after deleting a token causes another token to be deleted.

### ISSUE THREAD

**Issue by donusry** [Keyfactor/ejbca-ce#103]
I think this can only happen with unused crypto tokens.

EJBCA 7.4.3.2 Community official Docker container

Steps to reproduce:

1. Create three soft crypto tokens (e.g. test0, test1, test2).
2. Click delete by test0 and confirm.
3. Refresh the page. If it asks to resend data click ok.
4. test1 should disappear.
5. Refresh again.
6. test2 should disappear.

**Comment by primetomas** [comment]
The latest official docker container is 7.9.0.2, where there is a bug in crypto token deletion :-).
There will be a new release, 7.10 in a little while, should try with that.

**Comment by primetomas** [comment]
I could reproduce this however in the latest main branch. Thanks for reporting the issue. It's due to the "delete" button working on line number, and when deleting one crypto token the rest just moves up so hitting F5 resends a "delete crypto token on line number 6 in the UI view"

**Comment by donusry** [comment]
That's what I figured as well. I guess the positive is that if a token is in use it will error out. Not sure how often people have a sequential listing of unused tokens.

**Comment by primetomas** [comment]
While annoying, it's not annoying enough to prioritize compared to other issues unfortunately.
