### ISSUE TITLE
Release EJBCA CE 7.9.0.2 bad zip

### ISSUE THREAD

**Issue by Edelmeyder** [Keyfactor/ejbca-ce#113]
The downloaded file for the release [EJBCA CE 7.9.0.2](https://github.com/Keyfactor/ejbca-ce/releases/tag/EJBCA_7_9_0_2_20220616) has an "unexpected end of file" error. I downloaded it multiple times, both the .zip and the .tar.gz and its the same. I can still extract using tar command and I get a bunch of files but I though it best to post this issue in case some of the files are broken or something of the sort.
Cheers. Edelmiro.

**Comment by primetomas** [comment]
Perhaps a temporary glitch in GitHub? It's GitHub that created the zip/tgz. I just tried downloading the zip and there were no issues. The zip package is 134MB in size.
