### ISSUE TITLE
ejbca ce : protocol acme is Unavailable

### ISSUE THREAD

**Issue by carlosjpr-collab** [Keyfactor/ejbca-ce#125]
I am using ejbca ce using docker and i am trying to work with acme protocl but i saw this

![image](https://user-images.githubusercontent.com/38086105/193556107-d6e31aeb-c76a-4305-9f69-030d0b13859b.png)

Where the protocol acme is Unavailable. Why ?

How can i activate it ?. 

Its only for testing purpose.

**Comment by primetomas** [comment]
It's because ACME is so far an Enterprise feature. Sorry for having it visible there.
https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/protocols/acme
