### ISSUE TITLE
Docker keyfactor/ejbca-ce on ARM64

### ISSUE THREAD

**Issue by chaliy** [Keyfactor/ejbca-ce#145]
Hello team, could you please publish linux/arm64 image to https://hub.docker.com/r/keyfactor/ejbca-ce/ ? This will help to set up development boxes on Mac M1 notebooks. 

Under Mac AMD64 emulation, docker start is just hung at:

> [/opt/primekey/bin/start.sh] (process:1) Creating database tables...

**Comment by primetomas** [comment]
This is something we have into consideration, and doing some lab work. No ETA as of now though.

**Comment by primetomas** [comment]
Closing the issue while waiting. We have many users with M1 Macs as well.

**Comment by s17t** [comment]
+1, if you don't have arm64 iron at least provider Dockerfile sources to allow people built it. (see #1 )

**Comment by primetomas** [comment]
It's still in the works unfortunately. There's other pipe-line work that needed to be done first. But it's moving ahead at least.

**Comment by hablutzel1** [comment]
I've just realized the arm64 images are now available in https://hub.docker.com/r/keyfactor/ejbca-ce. Great!
