### ISSUE TITLE
Latest versions missing ejbca-setup.sh

### ISSUE THREAD

**Issue by adyfoot** [Keyfactor/ejbca-ce#158]
In the latest versions of EJBCA, the ejbca-setup.sh file is absent from the /bin/extras folder.  Assume this is a mistake?

**Comment by Realiserad** [comment]
I think Keyfactor removed it because they didn't want to maintain the script and EJBCA can be easily set up using as a container nowadays.

**Comment by primetomas** [comment]
Absolutely correct. 
The container is the easiest way to get started. 
There are also Ansible playbooks if you are looking to automate deployments, it's much more powerful that the old script. https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks
