### ISSUE TITLE
Publish JAR artifacts to OSSRH

### ISSUE THREAD

**Issue by Realiserad** [Keyfactor/ejbca-ce#168]
Hi, would it be possible to have EJBCA artifacts published to [OSSRH](https://central.sonatype.org/publish/publish-guide/), so that they can be included in pom.xml?

I'm primarily looking for the ``ejbca-common`` artifact which is needed when developing EJBCA plugins.

**Comment by Realiserad** [comment]
To expand a bit on the plugin part.

If you want to develop a custom publisher for EJBCA - using let's say Maven - you would need to provide the following jars at compile time:
```
<dependency>
    <groupId>org.ejbca</groupId>
    <artifactId>ejbca-common</artifactId>
    <version>7.10.0.2</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.cesecore</groupId>
    <artifactId>cesecore-common</artifactId>
    <version>7.10.0.2</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.cesecore</groupId>
    <artifactId>cesecore-entity</artifactId>
    <version>7.10.0.2</version>
    <scope>provided</scope>
</dependency>
```
 
The jars ``ejbca-common`` and ``cesecore-common`` can be found in Maven Central, but they are old, so I ended up building my own jars from source. There is no ant target for ``cesecore-entity`` so you need to rip it out from ``ejbca.ear``.

Then you can provide them locally, e.g. in ``lib`` and install them manually:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-install-plugin</artifactId>
    <executions>
        <execution>
            <id>install-ejbca-common</id>
            <phase>clean</phase>
            <configuration>
                <repositoryLayout>default</repositoryLayout>
                <groupId>org.ejbca</groupId>
                <artifactId>ejbca-common</artifactId>
                <version>7.10.0.2</version>
                <file>${project.basedir}/lib/ejbca-common.jar</file>
                <packaging>jar</packaging>
                <generatePom>true</generatePom>
            </configuration>
            <goals>
                <goal>install-file</goal>
            </goals>
        </execution>
        <execution>
          <id>install-cesecore-common</id>
          <phase>clean</phase>
          <configuration>
              <repositoryLayout>default</repositoryLayout>
              <groupId>org.cesecore</groupId>
              <artifactId>cesecore-common</artifactId>
              <version>7.10.0.2</version>
              <file>${project.basedir}/lib/cesecore-common.jar</file>
              <packaging>jar</packaging>
              <generatePom>true</generatePom>
          </configuration>
          <goals>
              <goal>install-file</goal>
          </goals>
      </execution>
      <execution>
        <id>install-cesecore-entity</id>
        <phase>clean</phase>
        <configuration>
            <repositoryLayout>default</repositoryLayout>
            <groupId>org.cesecore</groupId>
            <artifactId>cesecore-entity</artifactId>
            <version>7.10.0.2</version>
            <file>${project.basedir}/lib/cesecore-entity.jar</file>
            <packaging>jar</packaging>
            <generatePom>true</generatePom>
        </configuration>
        <goals>
            <goal>install-file</goal>
        </goals>
    </execution>
    </executions>
</plugin>
```

This is somewhat painful, and it would be great if Keyfactor could streamline this process a bit.

**Comment by primetomas** [comment]
What do you need cesecore-entity for for plugins?

**Comment by Realiserad** [comment]
> What do you need cesecore-entity for for plugins?

These are the warnings I get from Visual Studio Code if I don't declare ``cesecore-entity`` as a dependency.

> The type org.cesecore.oscp.OcspResponseData cannot be resolved. It is indirectly referenced from required type org.ejbca.core.model.ca.publisher.CustomPublisherContainerJava(16777563)

> The type org.cesecore.certificates.certificate.Base64CertData cannot be resolved. It is indirectly referenced from required type org.ejbca.core.model.ca.publisher.CustomPublisherContainerJava(16777563)

> The type org.cesecore.certificates.certificate.CertificateData cannot be resolved. It is indirectly referenced from required type org.ejbca.core.model.ca.publisher.CustomPublisherContainerJava(167775

**Comment by primetomas** [comment]
Sounds like a dependency bug there to me.

**Comment by primetomas** [comment]
@netmackan publishes cesecore-common as they are used by SignServer. @netmackan, is this a bug you would be affected by if it tries to pull in entity jars?

**Comment by primetomas** [comment]
There are new keyfactor-commons libraries being architected. These components will be much nicer and more reusable. Closing this issue. A smooth way to publish the new artifacts to maven, as released in the new pipe-line would be interesting.
