### ISSUE TITLE
Artistic License issue in modules/ra-gui/src/org/ejbca/ra/jsfext/RequestControlFilter.java 

### ISSUE THREAD

**Issue by Silviu-Caprar** [Keyfactor/ejbca-ce#179]
Hello,

As there is no information regarding the following reference from (https://github.com/Keyfactor/ejbca-ce/blob/EJBCA_7_9_0_2_20220616/modules/ra-gui/src/org/ejbca/ra/jsfext/RequestControlFilter.java)

 *  This file is licensed by original authors under an artistic license  *.

Can you please specify the full license of the artistic license which applies on this file ?

Thank you in advance for your answer.

**Comment by primetomas** [comment]
Thanks for the question. It will be clarified in the next release.
 *  This file is licensed by original authors under the artistic license.*
 *  See: https://opensource.org/licenses/artistic-license-1.0            *

And the full license included in doc/licenses in the EJBCA package.
