### ISSUE TITLE
Deploying EJBCA

### ISSUE THREAD

**Issue by Arlo001** [Keyfactor/ejbca-ce#196]
Please, I am trying to deploy an EJBCA community deployment according to the template on a test server locally, but when the command "ant -q clean deployear", I get the following error:

     [echo] No custom changes to merge.
     [echo] Cleaning cesecore-x509ca
     [echo] Cleaning va
     [echo] Cleaning ra
     [echo] appserver.home: $APPSRV_HOME
     [echo] appserver.type: <auto-detect>
     [echo] appserver.subtype: ${appserver.subtype}
     [echo] 
     [echo] ---------- EJBCA 7.10.0.2 Enterprise (working copy) CONFIGURATION PROPERTIES ----------
     [echo] appserver.type           = <auto-detect>
     [echo] appserver.subtype        = ${appserver.subtype}
     [echo] appserver.home           = $APPSRV_HOME
     [echo] java.version(ant.java)   = 11.0.17 (11)
     [echo] ocsp.signaturealgorithm  = SHA256WithRSA;SHA256withRSAandMGF1;SHA384WithRSA;SHA512WithRSA;SHA224withECDSA;SHA256withECDSA;SHA384withECDSA;SHA512withECDSA;SHA1WithDSA;Ed25519;Ed448
     [echo] datasource.jndi-name     = EjbcaDS
     [echo] datasource.jndi-name-prefix = java:/
     [echo] database.name            = mysql
     [echo] database.url             = jdbc:mysql://127.0.0.1:3306/ejbca?characterEncoding=UTF-8
     [echo] database.driver          = com.mysql.cj.jdbc.Driver
     [echo] database.username        = ejbca
     [echo] database.password        = ***
     [echo] database.useSeparateCertificateTable = false
     [echo] database.valid.connection.sql = select 1
     [echo] mail.jndi-name           = java:/EjbcaMail
     [echo] mail.from                = ejbca-donotreply@domain.com
     [echo] mail.user                = ejbca_user
     [echo] mail.password            = ***
     [echo] mail.smtp.host           = localhost
     [echo] mail.smtp.port           = 25
     [echo] mail.smtp.auth           = false
     [echo] mail.debug               = false
     [echo] httpserver.pubhttp	     = 8080
     [echo] httpserver.pubhttps	     = 8442
     [echo] httpserver.privhttps     = 8443
     [echo] httpserver.external.privhttps = 8443
     [echo] httpsserver.hostname     = 192.168.1.98
     [echo] httpsserver.password     = ***
     [echo] httpserver.external.fqdn = 
     [echo] web.contentencoding      = UTF-8
     [echo] web.renewalenabled       = false
     [echo] ejbcaws.enabled          = true
     [echo] unidfnr.enabled          = false
     [echo] 
     [echo]       
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /root/ejbca-ce/modules/cesecore-x509ca/src/org/cesecore/certificates/ca/X509CAImpl.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /root/ejbca-ce/modules/cesecore-ejb/src/org/cesecore/certificates/ca/CaSessionBean.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] /root/ejbca-ce/modules/ejbca-ejb-interface/src/org/ejbca/core/ejb/ra/EndEntityManagementSession.java:66: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    [javac]     void addUser(AuthenticationToken admin, String username, String password, String subjectdn, String subjectaltname, String email,
    [javac]          ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 warning
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /root/ejbca-ce/modules/publicweb-gui/src/org/ejbca/core/protocol/MSPKCS10RequestMessage.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /root/ejbca-ce/modules/healthcheck-war/src/org/ejbca/ui/web/pub/VaPeerStatusServlet.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

BUILD FAILED
/root/ejbca-ce/build.xml:848: The following error occurred while executing this line:
/root/ejbca-ce/build.xml:1511: The following error occurred while executing this line:
/root/ejbca-ce/modules/build.xml:260: The following error occurred while executing this line:
/root/ejbca-ce/modules/ejbca-ejb-cli/build.xml:126: /root/ejbca-ce/modules/$APPSRV_HOME does not exist.

Need your help to understand what is wrong 
Please help

**Comment by mike-agrenius-kushner** [comment]
See the [installation guide.](https://doc.primekey.com/ejbca/ejbca-installation/managing-ejbca-configurations)

You need to define an APPSRV_HOME (or declare it straight in ejbca.properties) pointing to the base directory of Wildfly, so that EJBCA knows where to deploy and bootstrap to.

Cheers,
Mike

**Comment by Arlo001** [comment]
Hello

Thank you for your feedback.

indeed I defined APPSRV_HOME in the environment variable as follows "export APPSRV_HOME =/opt/wildfly"
and also in the file ejbca.properties I have specified appserver.home=$APPSRV_HOME.
in addition all the other property files have been configured to the minimum as recommended.

But in relation to the failure I see that it is the build.xml files that I do not understand.

I am really stuck since and I wanted to advance in this project.

Thank you.

**Comment by primetomas** [comment]
The remove "appserver.home=$APPSRV_HOME". That is your problem, it shouldn't be there. The properties files do not expand environment variables like that and that is why the error says "/root/ejbca-ce/modules/$APPSRV_HOME does not exist".

**Comment by Arlo001** [comment]
Hi primetomas
Thank you for your feedback

indeed you are right
I changed that and put the real path of the application server and it worked.

Thanks

**Comment by primetomas** [comment]
If you set "export APPSRV_HOME..." you do not need to edit ejbca.properties as well. It is an OR condition there, use only one of the methods.

**Comment by Arlo001** [comment]
Thanks primetomas

On the other hand in the installation procedure, after the deployment of EJBCA, when I launch the installation with the command "ant runinstall" being in the directory "EJBCA_HOM", we have the following error:


Buildfile: /root/ejbca-ce/build.xml

customejbca.message:
     [echo] No custom changes to merge.
[available] DEPRECATED - <available> used to override an existing property.
[available]   Build file should not reuse the same property name for different values.

appserver.error.message:

runinstall:

check:bootstrapdone:

ejbca:prompt:
    [input] skipping input as property ca.name has already been set.
    [input] skipping input as property ca.dn has already been set.
    [input] skipping input as property ca.keytype has already been set.
    [input] skipping input as property ca.keyspec has already been set.
    [input] skipping input as property ca.signaturealgorithm has already been set.
    [input] skipping input as property ca.validity has already been set.
    [input] skipping input as property ca.policy has already been set.
     [echo] To set httpsserver.hostname you need to configure conf/web.properties. See sample config file conf/web.properties.sample.
    [input] skipping input as property httpsserver.hostname has already been set.
     [echo]
     [echo] Common Name (CN) of httpsserver dn is by default taken from the httpsserver.hostname.
    [input] skipping input as property httpsserver.dn has already been set.
    [input] skipping input as property superadmin.cn has already been set.
    [input] skipping input as property superadmin.dn has already been set.
    [input] skipping input as property superadmin.batch has already been set.
    [input] skipping input as property superadmin.password has already been set.
    [input] skipping input as property ca.tokenpassword has already been set.

ejbca:deploytrustprompt:
    [input] skipping input as property java.trustpassword has already been set.

ejbca:deployprompt:
    [input] skipping input as property httpsserver.password has already been set.

ejbca:init:
     [echo]
     [echo] ------------------- CA Properties ----------------
     [echo] ca.name                : ManagementCA
     [echo] ca.dn                  : CN=ManagementCA,O=EJBCA Sample,C=SE
     [echo] ca.tokentype           : soft
     [echo] ca.keytype             : RSA
     [echo] ca.keyspec             : 2048
     [echo] ca.signaturealgorithm  : SHA256WithRSA
     [echo] ca.validity            : 3650
     [echo] ca.policy              : null
     [echo] ca.tokenproperties     : ${ca.tokenproperties}
     [echo] httpsserver.hostname   : 192.168.1.98
     [echo] httpsserver.dn         : CN=192.168.1.98,O=EJBCA Sample,C=SE
     [echo] superadmin.cn          : SuperAdmin
     [echo] superadmin.dn          : CN=SuperAdmin,O=EJBCA Sample,C=SE
     [echo] superadmin.batch       : true
     [echo] appserver.home         : /opt/wildfly-26.0.0.Final
     [echo]

ejbca:install:

ejbca:initCA:
     [echo] Initializing CA with 'ManagementCA' 'CN=ManagementCA,O=EJBCA Sample,C=SE' 'soft' '<ca.tokenpassword hidden>' '2048' 'RSA' '3650' 'null' 'SHA256WithRSA'  -certprofile "ROOTCA" -superadmincn 'SuperAdmin'...
     [java] 09:00:35.545 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]

ejbca:adminweb:
     [java] 09:00:37.759 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]
     [java] 09:00:39.890 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]
     [echo] batch tomcat
     [java] 09:00:42.079 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]
     [java] 09:00:44.211 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]

ejbca:setclearpwd:
     [java] 09:00:46.433 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]

ejbca:batchsuperadmin:
     [echo] batch superadmin
     [java] 09:00:48.713 [main] ERROR org.ejbca.ui.cli.EjbcaEjbCli - Error: CLI could not contact EJBCA instance. Either your application server is not up and running, EJBCA has not been deployed successfully, or some firewall rule is blocking the CLI from the application server.
     [java]
     [java] Please be aware that most commands will not work without the application server available.
     [java]

BUILD FAILED
/root/ejbca-ce/build.xml:73: The following error occurred while executing this line:
/root/ejbca-ce/bin/cli.xml:98: The following error occurred while executing this line:
/root/ejbca-ce/bin/cli.xml:160: Batch generation failed!

Total time: 18 seconds

I would like to understand why, knowing that I went through the deployment step
Please give me your assistance

**Comment by primetomas** [comment]
You didn't check your server.log to verify that WildFly started correctly. As it says, EJBCA in WildFly is not running, you need to check that.

**Comment by Arlo001** [comment]
Hi

It is OK. 

Thanks
