### ISSUE TITLE
Rest Api for Revocation status not working

### ISSUE THREAD

**Issue by JibinNajeeb** [Keyfactor/ejbca-ce#201]
Using ejbca docker image of version 7.9.0.2

I tried the below api, 
`https://mycahostname:443/ejbca/ejbca-rest-api/v1/certificate/ManagementCA/21d574b25e4096aed016953638eecdde2a108b15/revocationstatus`

I'm getting below error as message while executing the api
![image](https://user-images.githubusercontent.com/47626138/209467309-e4fab8b0-b824-4c6e-a402-e33b55a874e5.png)

The attached file contains error logs I received
[error.txt](https://github.com/Keyfactor/ejbca-ce/files/10299914/error.txt)

Please help!!!

**Comment by primetomas** [comment]
The parameter ManagementCA is incorrect. It should be the URL encoded issuer DN of the certificate you check, i.e.
https://localhost:8443/ejbca/ejbca-rest-api/v1/certificate/CN%3DManagement%20CA%2CO%3DPK%2CC%3DSE/1234567890ABCDEF/revocationstatus
