### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by raydoom** [Keyfactor/ejbca-ce#211]
hareware：
Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz *2 
32 GB MEM
2TB RAID5 DISK

env:
MYSQL8.0 via docker
ejbca-ce:latest via docker 

As the amount of data in the UserData table increases, the performance drops from 200tps to 20tps (1000K row in UserData)
and the `show processlist` at mysql console show many like this:
`select 1 as col_0_0_ from UserData userdata0_ where trim(userdata0_.username)=trim('rskkh4cn1j')`
use `top` cmd show
```
top - 13:42:09 up 70 days,  2:43,  1 user,  load average: 18.29, 20.91, 21.99
Tasks: 733 total,   1 running, 732 sleeping,   0 stopped,   0 zombie
%Cpu(s): 73.5 us,  0.6 sy,  0.0 ni, 25.0 id,  0.8 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32408060 total,   551160 free,  7482272 used, 24374628 buff/cache
KiB Swap: 31453180 total, 31424508 free,    28672 used. 23806636 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 31592 polkitd   20   0 8333012 507172  11396 S  2165  1.6  19293:25 mysqld
 33270 10001     20   0   33.0g   1.0g  25848 S 203.6  3.3   1158:05 java
  3211 root      20   0   17.2g 808316  16776 S   2.0  2.5   3552:57 java
 31567 root      20   0 1572820   9688   1748 S   2.0  0.0  28:21.86 docker-proxy
  2929 gdm       20   0  650916  32720   9176 S   1.0  0.1 426:43.72 gsd-color
  1535 root      20   0 4012388 126604  30764 S   0.7  0.4 496:38.95 dockerd
  2721 polkitd   20   0 1113452  97788  15940 S   0.7  0.3 618:40.17 mongod
  4414 root      20   0 3859572  87872   8172 S   0.7  0.3   1363:46 lcsgo
 30054 root      20   0  114580  15168   3664 S   0.7  0.0  19:40.80 nsq_consumer
 43613 root      20   0  164852   3024   1624 R   0.7  0.0   0:00.11 top
  1224 root      20   0   90568   3228   2344 S   0.3  0.0   5:29.58 rngd
  2635 polkitd   20   0   11.3g 757996  11820 S   0.3  2.3 358:11.88 mysqld
  2840 root      20   0   30872  12300   1176 S   0.3  0.0 328:58.99 redis-server
  3499 root      20   0  113584  16464   4184 S   0.3  0.1 649:53.89 nsqd
 30013 root      20   0  398848  48148  15240 S   0.3  0.1   1:04.29 php
     1 root      20   0  191584   4560   2592 S   0.0  0.0  24:34.75 systemd
     2 root      20   0       0      0      0 S   0.0  0.0   0:06.06 kthreadd
     4 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
     6 root      20   0       0      0      0 S   0.0  0.0   1:03.63 ksoftirqd/0
     7 root      rt   0       0      0      0 S   0.0  0.0   0:07.20 migration/0
     8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
     9 root      20   0       0      0      0 S   0.0  0.0 133:05.68 rcu_sched
    10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain
    11 root      rt   0       0      0      0 S   0.0  0.0   0:19.06 watchdog/0
    12 root      rt   0       0      0      0 S   0.0  0.0   0:19.15 watchdog/1
    13 root      rt   0       0      0      0 S   0.0  0.0   0:07.59 migration/1
    14 root      20   0       0      0      0 S   0.0  0.0   0:27.41 ksoftirqd/1
    16 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H
    18 root      rt   0       0      0      0 S   0.0  0.0   0:16.56 watchdog/2
    19 root      rt   0       0      0      0 S   0.0  0.0   0:08.36 migration/2
    20 root      20   0       0      0      0 S   0.0  0.0   0:20.68 ksoftirqd/2
    22 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0H
    23 root      rt   0       0      0      0 S   0.0  0.0   0:16.10 watchdog/3
```

**Comment by raydoom** [comment]
when I remove the trim(), this is a big boost
```
 
mysql> select 1 as col_0_0_ from UserData userdata0_ where userdata0_.username='8qnq5njtac';
+----------+
| col_0_0_ |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)
 
mysql> select 1 as col_0_0_ from UserData userdata0_ where trim(userdata0_.username)=trim('8qnq5njtac');
+----------+
| col_0_0_ |
+----------+
|        1 |
+----------+
1 row in set (2.68 sec)
 
mysql>
```

**Comment by raydoom** [comment]
after run the  `create-index-ejbca.sql`
it is nothing changed
the performance drops to 10tps(1700K row in UserData) today

**Comment by primetomas** [comment]
The query should come from EndEntityAccessSessionBean.existsUser. trim is not done by EJBCA actually. This query does not cause any issues with databases with millions, or hundreds of millions of records actually, so it's interesting on your database configuration. 

EndEntityAccessSessionBean.existsUser simply does:
        final javax.persistence.Query query = entityManager.createQuery("SELECT 1 FROM UserData a WHERE a.username = :username");
and username is indexed. Not sure why it would use "trim"?

What kind of tables does your database use? InnoDB? 
I'm using MariaDB 10 and these are my numbers:

MariaDB [ejbca]> show create table UserData;
| UserData | CREATE TABLE `UserData` (
  `username` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `cAId` int(11) NOT NULL,
  `cardNumber` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `certificateProfileId` int(11) NOT NULL,
  `clearPassword` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `endEntityProfileId` int(11) NOT NULL,
  `keyStorePassword` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `passwordHash` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `rowVersion` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `subjectAltName` varchar(8192) DEFAULT NULL,
  `subjectDN` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `subjectEmail` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `timeCreated` bigint(20) NOT NULL,
  `timeModified` bigint(20) NOT NULL,
  `tokenType` int(11) NOT NULL,
  `type` int(11) NOT NULL,
  `extendedInformationData` longtext DEFAULT NULL,
  `rowProtection` longtext DEFAULT NULL,
  `hardTokenIssuerId` int(11) NOT NULL,
  PRIMARY KEY (`username`),
  KEY `userdata_idx10` (`subjectDN`(255)),
  KEY `userdata_idx11` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci |

> select 1 as col_0_0_ from UserData userdata0_ where trim(userdata0_.username)=trim('rskkh4cn1j')
Empty set (1,010 sec)
second time it's cached:
Empty set (0,000 sec)

I have 1327524 records in UserData.

A stress test with:
./ejbcaClientToolBox.sh EjbcaWsRaCli stress ManagementCA 10 10

gives me 100-150 certificates per second n my laptop. Admittedly I didn't try to replicate your exact environment.


How are you measuring performance? I.e. what is 10tps?

A bit strange actually, I enabled SQL logging in hibernate and it doesn't show any trim.
>bin/jboss-cli.sh -c
/subsystem=logging/logger=org.hibernate.SQL:add
/subsystem=logging/logger=org.hibernate.SQL:write-attribute(name=level, value=DEBUG)

Checking in server.log shows:
2023-01-16 11:35:34,311 DEBUG [org.hibernate.SQL] (default task-18) select 1 as col_0_0_ from UserData userdata0_ where userdata0_.username=?

**Comment by raydoom** [comment]
After I update the docker image from 
`keyfactor/ejbca-ce:latest (keyfactor/ejbca-ce       latest    f253c6e8609f   6 weeks ago     446MB)`
to
`keyfactor/ejbca-ce: 7.11.0(keyfactor/ejbca-ce       7.11.0    d7633bc9a2dd   44 hours ago    565MB)`
the trim() sql has be removed, 
As you said, it show like 
`select 1 as col_0_0_ from UserData userdata0_ where userdata0_.username=?`

I test the performance with image keyfactor/ejbca-ce: 7.11.0,it is no problem for me now，the performance is good

By say,I use jmeter to test the performance with RESTAPI
`https://ip:443/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll`

thanks for you and your team
