### ISSUE TITLE
SM3WithSM2 and SM3 support

### ISSUE THREAD

**Issue by raydoom** [Keyfactor/ejbca-ce#218]
I find that this system support `sm2p256v1 `
But no `SM3WithSM2` and `SM3` 
Is it not supported now?

**Comment by primetomas** [comment]
Correct, the signature algorithm SM3WithSM2 is not supported in EJBCA. Although the underlying Bouncy Castle support it, there has not been enough/much demand to add it to EJBCA.
Adding a new signature algorithm is not that hard. Pull requests are accepted :-).

**Comment by raydoom** [comment]
Got it

**Comment by primetomas** [comment]
Closing. Community PRs can be done here. Commercial feature requests can be issued to Keyfactor.
