### ISSUE TITLE
ejbca won't start with freshly created db structure

### ISSUE THREAD

**Issue by lazydays79** [Keyfactor/ejbca-ce#24]
With ECA-8029 the support for hard tokens was dropped and hence the `hardTokenIssuerId` field from the `UserData` table was dropped, see here:

https://github.com/primekeydevs/ejbca-ce/commit/a0c4e17ebc72d1b9eb16f0470aedcb64cb5708a2

But the `UserData` entity class still requires the `hardTokenIssuerId` to be present:

https://github.com/primekeydevs/ejbca-ce/blob/10c9d316789d68c56b9bf67fc60f268d6353ff46/modules/ejbca-entity/src/org/ejbca/core/ejb/ra/UserData.java#L80

There should either be a `@Transient` annotation present on that property or the scripts in `doc/sql-scripts/*` should still contain that property. Otherwise ejbca will fail to deploy:

~~~
11:43:32,620 INFO  [org.hibernate.event.internal.DefaultLoadEventListener] (ServerService Thread Pool -- 39) HHH000327: Error performing load command : org.hibernate.exception.SQLGrammarException: could not extract ResultSet
11:43:32,630 ERROR [org.jboss.as.ejb3.invocation] (ServerService Thread Pool -- 39) WFLYEJB0034: EJB Invocation failed on component AuthorizationSystemSessionBean for method public abstract boolean org.ejbca.core.ejb.authorization.AuthorizationSystemSessionLocal.initializeAuthorizationModule(): javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
[...]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'userdata0_.hardTokenIssuerId' in 'field list'
Query is : select userdata0_.username as username1_34_0_, userdata0_.cAId as cAId2_34_0_, userdata0_.cardNumber as cardNumb3_34_0_, userdata0_.certificateProfileId as certific4_34_0_, userdata0_.clearPassword as clearPas5_34_0_, userdata0_.endEntityProfileId as endEntit6_34_0_, userdata0_.hardTokenIssuerId as hardToke7_34_0_, userdata0_.keyStorePassword as keyStore8_34_0_, userdata0_.passwordHash as password9_34_0_, userdata0_.rowVersion as rowVers10_34_0_, userdata0_.status as status11_34_0_, userdata0_.subjectAltName as subject12_34_0_, userdata0_.subjectDN as subject13_34_0_, userdata0_.subjectEmail as subject14_34_0_, userdata0_.timeCreated as timeCre15_34_0_, userdata0_.timeModified as timeMod16_34_0_, userdata0_.tokenType as tokenTy17_34_0_, userdata0_.type as type18_34_0_, userdata0_.extendedInformationData as extende19_34_0_, userdata0_.rowProtection as rowProt20_34_0_ from UserData userdata0_ where userdata0_.username='ejbca'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:213)
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:185)
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:143)
	at org.jboss.jca.adapters.jdbc.CachedPreparedStatement.executeQuery(CachedPreparedStatement.java:113)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	... 166 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Unknown column 'userdata0_.hardTokenIssuerId' in 'field list'
Query is : select userdata0_.username as username1_34_0_, userdata0_.cAId as cAId2_34_0_, userdata0_.cardNumber as cardNumb3_34_0_, userdata0_.certificateProfileId as certific4_34_0_, userdata0_.clearPassword as clearPas5_34_0_, userdata0_.endEntityProfileId as endEntit6_34_0_, userdata0_.hardTokenIssuerId as hardToke7_34_0_, userdata0_.keyStorePassword as keyStore8_34_0_, userdata0_.passwordHash as password9_34_0_, userdata0_.rowVersion as rowVers10_34_0_, userdata0_.status as status11_34_0_, userdata0_.subjectAltName as subject12_34_0_, userdata0_.subjectDN as subject13_34_0_, userdata0_.subjectEmail as subject14_34_0_, userdata0_.timeCreated as timeCre15_34_0_, userdata0_.timeModified as timeMod16_34_0_, userdata0_.tokenType as tokenTy17_34_0_, userdata0_.type as type18_34_0_, userdata0_.extendedInformationData as extende19_34_0_, userdata0_.rowProtection as rowProt20_34_0_ from UserData userdata0_ where userdata0_.username='ejbca'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:870)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQueries(AbstractQueryProtocol.java:789)
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:177)
	... 170 more
~~~

**Comment by primetomas** [comment]
What's your environment? I just dropped the hardTokenIssuerID column from the UserData table in my old database, and everything works great. My: JBoss EAP 7.3, MariaDB 10.x, EJBCA 7.8.x

The mapping in EJBCA is not dynamic from the fields in the class, due to various inflexibilities with that we use orm files that maps the field to database columns. See modules/ejbca-entity/resources/orm/orm-ejca-mysql.xml.

**Comment by lazydays79** [comment]
We found this issue during our investigation for #22.

For that we created a gitlab build pipeline in which we defined a MariaDB container as a service, imported the create-tables-ejbca-mysql.sql into it and then automaticaly deploy ejbca.ear into a wildfly container.

Used versions:

- ejbca 7.4.3.2
- wildfly 14.0.1.Final
- mariadb 10.2

**Comment by primetomas** [comment]
I ran some tests...Have you restricted privileges to the database so that UserData can not be modified? When I test, indeed hardTokenIssuerID will be created automatically in the database, and if I drop it it will be re-added. So I assume that your application server does not have privileges to alter the table (which may be a good idea to have this limitation for sure).

Is it so?

**Comment by lazydays79** [comment]
We used the same user we used for executing the create tables sql script.

It was defined by the MYSQL_USER and MYSQL_PASSWORD environment variables, so the user had all privileges as defined in the maria db container documentation:

https://hub.docker.com/_/mariadb

**Comment by primetomas** [comment]
I used this command to launch a community container, and it works perfect. What's the difference in what you are doing?

sudo docker run -it --rm -p 80:8080 -p 443:8443 -h localhost -e TLS_SETUP_ENABLED="simple" -e DATABASE_JDBC_URL="jdbc:mysql://127.0.0.1:3306/ejbcatest?characterEncoding=UTF-8" -e DATABASE_USER="ejbca" -e DATABASE_PASSWORD="ejbca" --network="host" primekey/ejbca-ce

**Comment by primetomas** [comment]
For now, add the column to the database and everything should work perfect. I created this issue to make it smoother.
https://jira.primekey.se/browse/ECA-10591

**Comment by primetomas** [comment]
Turns out the correct fix is to add back hardTokenIssuerId to the database table orm file and sql script. The field must be there for backwards compatibility reasons.

CREATE TABLE UserData (
    username VARCHAR(250) BINARY NOT NULL,
    cAId INT(11) NOT NULL,
    cardNumber VARCHAR(250) BINARY,
    certificateProfileId INT(11) NOT NULL,
    clearPassword VARCHAR(250) BINARY,
    endEntityProfileId INT(11) NOT NULL,
    extendedInformationData LONGTEXT,
    hardTokenIssuerId INT(11) NOT NULL,
    keyStorePassword VARCHAR(250) BINARY,
    passwordHash VARCHAR(250) BINARY,
    rowProtection LONGTEXT,
    rowVersion INT(11) NOT NULL,
    status INT(11) NOT NULL,
    subjectAltName VARCHAR(2000) BINARY,
    subjectDN VARCHAR(767) BINARY,
    subjectEmail VARCHAR(256) BINARY,
    timeCreated BIGINT(20) NOT NULL,
    timeModified BIGINT(20) NOT NULL,
    tokenType INT(11) NOT NULL,
    type INT(11) NOT NULL,
    PRIMARY KEY (username)
);
