### ISSUE TITLE
start.sh fails to read memory limit with cgroup2

### ISSUE THREAD

**Issue by nvollmar** [Keyfactor/ejbca-ce#240]
Running ejbca with cgroup2 fails to read memory limits:
```
cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory
```

Workaround is to manually set memory arguments via env variable.

**Comment by primetomas** [comment]
When do you get this? When running a CLI command? When starting the EJBCA container?
EJBCA does not try to read any such values itself, that would be a java thing perhaps, related to you JDK?

**Comment by nvollmar** [comment]
Sorry, I may have been imprecise. This happens in the `start.sh` when running the ejbca docker image.
The start script tries to read the memory limits to set the proper -xmx etc to start the JVM.

When running it with cgroup 2, that path is not available and the read fails.

**Comment by primetomas** [comment]
Thanks. We'll take a look.

**Comment by primetomas** [comment]
Sorry for the slow work. I have created an internal issue for the developers to fix it.

**Comment by hablutzel1** [comment]
I've just stumbled upon this on a Debian 11 Docker host, which uses cgroup v2 by default (see https://github.com/opencontainers/runc/blob/main/docs/cgroup-v2.md).

The following patch fixes this:

```patch
--- a/start.sh
+++ b/start.sh
@@ -99,9 +99,16 @@
 fi
 
 # Calculate memory available to the container
-memCgroup=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
+if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ] ; then
+  memCgroup=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
+elif [ -f /sys/fs/cgroup/memory.max ] ; then
+  memCgroup=$(cat /sys/fs/cgroup/memory.max)
+else
+  log "ERROR" "Expected cgroup file not found. Aborting startup."
+  exit 1
+fi
 memTotal=$(cat /proc/meminfo | awk '/MemTotal/ {print $2*1024}')
-if [ ${memCgroup:-0} != -1 ] && [ ${memCgroup:-0} -lt ${memTotal} ] ; then
+if [ $memCgroup != -1 ] && [ $memCgroup != "max" ] && [ $memCgroup -lt ${memTotal} ] ; then
   memLimit=${memCgroup}
   log "INFO" "Detected $memLimit bytes available memory assigned to this container."
 else

```

**Comment by primetomas** [comment]
Thanks. MR created in the internal repo. Closing for now, hoping it appears in the wild soon-ish :-).
