### ISSUE TITLE
OCSP failures with Java 17

### ISSUE THREAD

**Issue by MastaP** [Keyfactor/ejbca-ce#25]
We're running EJBCA-ce version 7.4.3.2.

Our services are running fine on Java 15 and 16, but once we tried upgrading to 17 (without changing anything else), our OCSP certificate revocation tests started failing with the following:

```
Caused by: java.security.cert.CertPathValidatorException: OCSP response error: MALFORMED_REQUEST
	at java.base/sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:389)
	at java.base/sun.security.provider.certpath.OCSP.check(OCSP.java:199)
	at java.base/sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:785)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:369)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 90 more
	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
		at java.base/sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1152)
		at java.base/sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:972)
		at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:611)
		at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:471)
		at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:400)
```

I did some research and there might have been some changes that could affect:
https://www.oracle.com/java/technologies/javase/17-relnote-issues.html

> It also applies to the signature and digest algorithms of the certificates in the certificate chain of the code signer and the Timestamp Authority, and any CRLs or OCSP responses that are used to verify if those certificates have been revoked.

and there is a fix (not sure if it's relevant or not) in the commercial version of EJBCA (7.8.0.1):

> CRL and OCSP Validity Compliance
It was brought to our attention by a customer that EJBCA adds a second of validity to CRLs and OCSP replies to what is intended in RFC 5280. This issue has been addressed in EJBCA 7.8.0.1 by reducing the validity of CRLs and OCSP responses by 1 second

https://doc.primekey.com/ejbca/ejbca-release-information/ejbca-release-notes/ejbca-7-8-0-release-notes

Any ideas on how to fix this problem in CE?

**Comment by Realiserad** [comment]
EJBCA CE and EJBCA EE is only (officially) compatible with Java 8 and Java 11 at the moment. I believe PrimeKey's next target JDK will be 17, but that's probably not going to be on the roadmap until the next major release (i.e. EJBCA 8).

**Comment by Realiserad** [comment]
> and there is a fix (not sure if it's relevant or not) in the commercial version of EJBCA (7.8.0.1):

The "CRL and OCSP Validity Compliance" thing is only to satisfy the [BR boffins](https://cabforum.org/baseline-requirements-documents/).

In this case it looks more like someone sent a malformed OCSP request. It could be related to Java 17, does this happen all the time?

**Comment by MastaP** [comment]
> In this case it looks more like someone sent a malformed OCSP request to EJBCA. Can you see anything in the application server log?

Our application sends OCSP requests to EJBCA. On Java 15&16 this request passes, but after switching to 17 it fails with the exception above. The code is straightforward and has not been changed:
```kotlin
    fun verifyCertificate(certificate: X509Certificate): Boolean {
        val cf: CertificateFactory = CertificateFactory.getInstance("X.509")
        val certPath: CertPath = cf.generateCertPath(listOf(certificate))
        val params = PKIXParameters(trustStore).apply {
            isRevocationEnabled = isOCSPEnabled
        }
        Security.setProperty("ocsp.enable", isOCSPEnabled.toString())

        val validator = CertPathValidator.getInstance("PKIX")
        validator.validate(certPath, params)
        ...
```

**Comment by MastaP** [comment]
> EJBCA CE and EJBCA EE is only (officially) compatible with Java 8 and Java 11 at the moment.

we're not running EJBCA on Java 17, we tried running our app on 17 which sends OCSP requests to EJBCA running inside a standard Docker container

**Comment by primetomas** [comment]
In the server log of EJBCA you should be able to see why the request is considered Malformed by the server. Check server.log. If needed enable DEBUG logging so see all details. Sounds like there is something with the request itself that Java 17 does differentl.

**Comment by primetomas** [comment]
any news @MastaP ?

**Comment by MastaP** [comment]
I had some other priorities (with a workaround of staying below java17), but I'll try to come back to this issue later this week or the next one

**Comment by MastaP** [comment]
Okay, issue solved. 
The error `Error processing OCSP request. Message: Request is missing last part of URL defined in RFC 2560 A.1.1` was caused by our haproxy instance that was throwing away the last part of the request URLs. 
Old Javas were sending POST with the request body, Java17 now sends `GET {url}/{url-encoding of base-64 encoding of the DER encoding of the OCSPRequest}` instead of POST.

**Comment by primetomas** [comment]
Ah, cool to know that Java17 uses OCSP GET instead of POST. Thanks for the update.
