### ISSUE TITLE
CMP server is unable to recognize IPv6 address

### ISSUE THREAD

**Issue by hfzqasim** [Keyfactor/ejbca-ce#264]
I am using openssl CMP client to send IR request. In the request I am adding one IPv4 address and one IPv6 address as shown in the tcpdump, 

![image](https://user-images.githubusercontent.com/127116175/226654327-e4f1cb0b-8937-44a1-815e-e6c301290b41.png)

but seems like the CMP server is unable to recognize IPv6 address and ignore it,

15:21:08,784 INFO  [org.cesecore.util.StringTools] (default task-1) Not a IPv4 or IPv6 address, returning empty array.
15:21:08,784 ERROR [org.cesecore.util.CertTools] (default task-1) **Cannot parse/encode ip address, ignoring: null**
15:21:08,784 INFO  [org.cesecore.util.StringTools] (default task-1) Not a IPv4 or IPv6 address, returning empty array.
15:21:08,784 ERROR [org.cesecore.util.CertTools] (default task-1) **Cannot parse/encode ip address, ignoring: null**
15:21:08,791 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-1) 2023-03-21 15:21:08+00:00;CERT_STORED;SUCCESS;CERTIFICATE;CORE;10.144.210.158;1733764446;3B1A6678AD91F97614B7D108A1217A96E55C2D0F;192.168.8.15;msg=Certificate stored for username '192.168.8.15', fp=2ca5d5a35b9fa0d2d618334816b5877cb8b2730b, subjectDN 'CN=192.168.8.15', issuerDN 'UID=c-IHM5CJTGXJBmxLufCugRqiJLPctekPSf,CN=ManagementCA,O=Example CA,C=SE', serialNo=3B1A6678AD91F97614B7D108A1217A96E55C2D0F, accountBindingId=.
15:21:08,794 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-1) 2023-03-21 15:21:08+00:00;CERT_CREATION;SUCCESS;CERTIFICATE;CORE;10.144.210.158;1733764446;3B1A6678AD91F97614B7D108A1217A96E55C2D0F;192.168.8.15;subjectdn=CN=192.168.8.15;certprofile=1929009280;issuancerevocationreason=-1;cert=MIIEJDCCAoygAwIBAgIUOxpmeK2R+XYUt9EIoSF6luVcLQ8wDQYJKoZIhvcNAQELBQAwbTEyMDAGCgmSJomT8ixkAQEMImMtSUhNNUNKVEdYSkJteEx1ZkN1Z1JxaUpMUGN0ZWtQU2YxFTATBgNVBAMMDE1hbmFnZW1lbnRDQTETMBEGA1UECgwKRXhhbXBsZSBDQTELMAkGA1UEBhMCU0UwHhcNMjMwMzIxMTUxMTA4WhcNMjUwMzIwMTUxMTA3WjAXMRUwEwYDVQQDDAwxOTIuMTY4LjguMTUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlQW+TMyGkhpuDmhhteJTkSVdKa+HWoBhFNKOA3t3OJe7hQLJ+xLq/s66R5LTpje0sCo74C4z+pwxEt5fvVfFtNynD9vQ9VI5KAATTtUGHYzmNDt1ZoN/XhzVxsA0gM9Snr9PqPGB6zAFxeh3rVy5HNT52l0Cj9cwTLwVz6nI/dozHEA7RxmE5oHxOpzM+sWkdAjQGCI5q12EL0CgPfSxxFWuhBnp6U0uNE3Q9qRAaYTvewRVvjPwI7fnbas3x3a6yXQr1TP03UceqgKn5IOYNMNAss4nY830XY4ieqi6Hrbx1+WVGcFe17k6qOCLbaQnBMamWH8KFIuulhiEI46f1AgMBAAGjgZEwgY4wDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSzfnTA6k2MiewTh8/Zw4VZ6WDC5jAPBgNVHREECDAGhwTAqAEPMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAdBgNVHQ4EFgQUxtPoaN4V5mWojt+agGAGTTlofwEwDgYDVR0PAQH/BAQDAgXgMA0GCSqGSIb3DQEBCwUAA4IBgQAd/YCsZUuKkwTmKF039irpSCekHNfUt3AVzVzswkNlYGmsq2Z2RdoRin8UsNMnM30S2Pnql9B8u0f8+ID0m7urmhzTcE6GmISXODHnJlbgV9TFcthQR/TXPxvT8fJbAlaUB3GKPjqoIz9kdP8nVTk9F3hsQ/LHiqway+B0HiqfJh3iS3iUpu8Wv3hKXCJ0KQh0Q6BtX93J26oRttKrKobfszA2lUfjqEPaiAJR8xnpLtmBfU3WDBrBNPx6EdZbQS1YFT1gNAzVSKTOAkXlTCUqPQYn4nrF5mRyE5dAkCoyo7uGf8o7+5OE/uUlHqkOAov6gDaGvDekP6JAYBSTWXK6lRT1wE/Cw6WJ13QwsDtCLut234MJrRFpzQz8VwgsjpWXadiSYR4RXA4cAEr9ELn0PzRCW9jeIM5Sy8zXzd+1j/H4Fq3rP1jrgk+LPR/gMN4yjsDRxfjPzhaJBK3pGudNHHKVOUDLuvZOkQJnw8iHiMLp8K3+RNqSmXDeaNnwxt8=
15:21:08,797 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-1) 2023-03-21 15:21:08+00:00;RA_EDITENDENTITY;SUCCESS;RA;CORE;Local admin call from EndEntityManagementSession.decRequestCounter;1733764446;;192.168.8.15;msg=Edited end entity 192.168.8.15, new status 40.
15:21:08,799 INFO  [org.ejbca.core.ejb.ra.EndEntityManagementSessionBean] (default task-1) Changed status for '192.168.8.15' to STATUS_GENERATED.

the certificate I receive only contains IPv4 address, please check.

**Comment by primetomas** [comment]
Looks like a formatting issue in the passed in ipv6 issue?

This is the pattern used to judge if it is an ipv6 address.

private static final String ipv6Pattern = "^([\\dA-F]{1,4}:|((?=.*(::))(?!.*\\3.+\\3))\\3?)([\\dA-F]{1,4}(\\3|:\\b)|\\2){5}(([\\dA-F]{1,4}(\\3|:\\b|$)|\\2){2}|(((2[0-4]|1\\d|[1-9])?\\d|25[0-5])\\.?\\b){4})\\z";
Matcher m2 = StringTools.VALID_IPV6_PATTERN.matcher(ipAddress);
return m2.matches();

**Comment by hfzqasim** [comment]
Alright, I think this pattern is not fully correct as it expects HEX characters A-F in capitals, but IPv6 address can be given in small HEX characters also.

Moreover, I am trying different IPv6 address formats and still I am not able to get a certificate having IPv6 address as its SAN

Examples I have tried
FD00:DEED:ACDC:1908:0:0:0:208
FD00:DEED:ACDC:1908::208
FD00:DEED:ACDC:1908:0000:0000:0000:0208

All these examples are not working, could you provide an IPv6 address example which should work?

**Comment by primetomas** [comment]
Here are some examples we have in the test for this method:
        final String ipV6Example1 = "2001:0db8:3333:4444:5555:6666:7777:8888";        
        final String ipV6Example3 = "2001:db8::";
        final String ipV6Example4 = "2001:db8::1234:5678";
        final String ipV6Example5 = "::1234:5678";
        final String ipV6Example6 = "2001:0db8:0001:0000:0000:0ab9:C0A8:0102";

**Comment by hfzqasim** [comment]
unfortunately, all above examples failed. I tried to send IR request with OpenSSL CMP client by providing this flag in the request
-sans "2001:0db8:0001:0000:0000:0ab9:C0A8:0102"

In the tcpdump, I was able to see that the request was having this IPv6 address, but the certificate I received does not have this IPv6 address. Please note that IPv4 is working fine.

I am using EJBCA 7.11.0 Community

**Comment by hfzqasim** [comment]
public static String ipOctetsToString(final byte[] octets) {
        String ret = null;
        if (octets.length == 4) {
            String ip = "";
            // IPv4 address
            for (int i = 0; i < 4; i++) {
                // What is going on there is that we are promoting a (signed) byte to int,
                // and then doing a bitwise AND operation on it to wipe out everything but
                // the first 8 bits. Because Java treats the byte as signed, if its unsigned
                // value is above > 127, the sign bit will be set, and it will appear to java
                // to be negative. When it gets promoted to int, bits 0 through 7 will be the
                // same as the byte, and bits 8 through 31 will be set to 1. So the bitwise
                // AND with 0x000000FF clears out all of those bits.
                final int intByte = 0x000000FF & octets[i];
                final short t = (short) intByte; // NOPMD, we need short
                if (StringUtils.isNotEmpty(ip)) {
                    ip += ".";
                }
                ip += t;
            }
            ret = ip;
        }
        **// TODO: IPv6**
        return ret;
    }

**Comment by primetomas** [comment]
Yeah, that could be it for sure. I knew about this sometime ago but had forgotten about it. You wouldn't know how to convert the octet string into ipv6 readable text, and create a PR?

**Comment by primetomas** [comment]
How would you do it in Go? Perhaps I can translate it to Java. I just don't have time to do that from scratch.

**Comment by hfzqasim** [comment]
Golang has builtin support for such conversions
example code on Go playground
https://go.dev/play/p/gwYbqsDEzyV
