### ISSUE TITLE
[Feature Req] Certificate REST API v2 enrollPkcs10Certificate: allow overwriting DN

### ISSUE THREAD

**Issue by uedvt359** [Keyfactor/ejbca-ce#266]
We would like to be able to create end entities and certificates with the RESTv2 enrollPkcs10Certificate endpoint, but without trusting the DN that's in the CSR.

This is possible with the old SOAP API by using `CertificateResponse certificateRequest()`. By setting `userData` the entity's DN (among other data) can be set.

**Comment by primetomas** [comment]
I guess you mean /v1/certificate/pkcs10enroll?

You can't do that in a single call with REST yet. You need:

/v1/endentity]
followed by:
/v1/certificate/certificaterequest

**Comment by uedvt359** [comment]
Yes, that's the endpoint. IMO having to do a second API call (and all the associated error handling) is less convenient than what SOAP offers, not least because /v1/endentity is an enterprise feature.

pkcs10enroll already creates end entities, it just doesn't allow overriding parameters inside the CSR.

I can live with this being closed as WONTFIX, if I'm interpreting your comment correctly.

**Comment by primetomas** [comment]
Closing as not planned at the moment, but watch this space, it has been asked before.
