### ISSUE TITLE
SCP Publisher Alternative Port

### ISSUE THREAD

**Issue by gareththered** [Keyfactor/ejbca-ce#275]
There isn't the equivalent of  `scp -P <port number>` option on the SCP Publisher configuration page.

I'm currently using a General Purpose Custom Publisher to run a script which runs the `scp` command (with alt port) to push CRLs to a repository, which is running as a container.  I can't listen on port 22 as that's used by the container host, so am using an alternative port.  I was hoping the SCP Publisher would enable me to get rid of the scripts that the GP Custom Publisher runs, but without an option for an alternative port, I'm scuppered.

Could this option be added?

**Comment by LachlanDodd** [comment]
@gareththered 
As a work around until this is configurable in the GUI you try setting the port in the ssh host configuration.
**Edit/Create** .ssh/config 
**Add the host and port e.g**
Host scp.host
    Port 2222

**Comment by gareththered** [comment]
That's interesting.  I wasn't aware it was using the host's SSH.  Good to know, and yes, a simple workaround.
