### ISSUE TITLE
Client does not support authentication protocol requested by server. plugin type was = 'sha256_password'

### ISSUE THREAD

**Issue by bsjaramillo** [Keyfactor/ejbca-ce#282]
Steps to reproduce:
sudo docker run -it --rm -p 80:8080 -p 443:8443 -h mycahostname -e "DATABASE_JDBC_URL=jdbc:mysql://localhost:3306/ejbca" -e "DATABASE_USER=ejbca" -e "DATABASE_PASSWORD=password" keyfactor/ejbca-ce

**Comment by primetomas** [comment]
Is that a configuration of your MariaDB/MySQL server running on localhost?
Internally the container uses the MariaDB-java-client version 3.1.0, so whatever methods this jdbc driver supports, your server can use. Of course, if you want to use client certificates, you need to find a way to get that into the container and configure the JDBC connect string accordingly in DATABASE_JDBC_URL.

Typically you would map the database hostname to something else than localhost wouldn't you?

**Comment by primetomas** [comment]
Thanks. You can also try MariaDB container, I think it's more commonly used.
