### ISSUE TITLE
docker-compose file in documentation is incorrect

### ISSUE THREAD

**Issue by fuomag9** [Keyfactor/ejbca-ce#303]
https://doc.primekey.com/ejbca/tutorials-and-guides/tutorial-start-out-with-ejbca-docker-container

The example docker-compose file here has one missing space in the `container_name` key:
![image](https://github.com/Keyfactor/ejbca-ce/assets/1580624/7b358e48-c5ad-41f6-a667-389a62dba6a3)

**Comment by primetomas** [comment]
Thanks. There was actually a tab instead of spaces. Fixed for the next doc release.

**Comment by primetomas** [comment]
Update published online
