### ISSUE TITLE
Broken link in docker hub documentation 

### ISSUE THREAD

**Issue by fuomag9** [Keyfactor/ejbca-ce#304]
The additional examples links to [here](https://github.com/Keyfactor/ejbca-containers) but that link is dead
![image](https://github.com/Keyfactor/ejbca-ce/assets/1580624/280f1b15-e877-4482-a5c9-7c89ae33f056)

**Comment by primetomas** [comment]
Thanks. Someone moved that repo. I updated the documentation.
