### ISSUE TITLE
Error when building version 8.0.0 with Java 11

### ISSUE THREAD

**Issue by miguelarman** [Keyfactor/ejbca-ce#316]
I am trying to upgrade my EJBCA deployment from version 7.11.0 to the newest 8.0.0. As I can see on the [release notes](https://doc.primekey.com/ejbca/ejbca-release-information/ejbca-release-notes/ejbca-8-0-release-notes#EJBCA8.0ReleaseNotes-RunningonJava8notsupported), Java version 8 (which I was using) is now deprecated, so I previously upgraded to Java 11.

My problem comes when executing ```ant deployear``` to start the new deployment. When it starts to build the ```admin-gui``` module, inside the ```setup``` target, ```ant``` calls a module called ```native2ascii```. As I have been researching online, this was deprecated all the way back in Java 9 [(link)](https://bugs.openjdk.org/browse/JDK-8074431).
```
<native2ascii encoding="UTF-8"
    src="${admin-gui.resources.dir}/languages"
    dest="${admin-gui.build.dir}/languages"
    includes="languagefile.*.properties" 
    excludes="languagefile.zh.properties"
/>
<native2ascii encoding="GBK"
    src="${admin-gui.resources.dir}/languages"
    dest="${admin-gui.build.dir}/languages"
    includes="languagefile.zh.properties" 
/>
```

I found two alternatives that helped me:

1. Manually copying the related files (those called ```languagefile.*.properties``` inside the resources folder to the build folder) and commenting this target.
2. Modifying this targets to use the ```copy``` module instead:
```
<copy todir="${admin-gui.build.dir}/languages" >
    <fileset dir="${admin-gui.resources.dir}/languages" includes="languagefile.*.properties"/>  
</copy>
```

Both allow the compilation and deployment to continue and finish successfully.

My question is if this is the method to be used, or if I am doing something wrong when it comes to deploying the application. Furthermore, I wonder if the ```build.xml``` for the ```admin-gui``` module needs to be modified for future releases.

Thanks in advance

**Comment by primetomas** [comment]
What java are you using? For me it works with a simple "apt install openjdk-11-jdk-headless" in Ubuntu 22.04.

java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

**Comment by miguelarman** [comment]
Thanks for your response and sorry for my delayed answer

I am using a Virtual Machine running "SUSE Linux Enterprise Server 12 SP3" with java version:
```
# java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+0-suse-3.52.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.18+0-suse-3.52.1-x8664, mixed mode)
```

**Comment by primetomas** [comment]
I installed the latest version of OpenSUSE Leap 15.5 and it works for me.

Something like.

```
sudo zypper install java-11-openjdk
sudo zypper install ant
sudo update-alternatives --config java
(select Java 11)

>java -version
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+0-suse-150000.3.99.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.20+0-suse-150000.3.99.1-x8664, mixed mode)

git clone https://github.com/Keyfactor/ejbca-ce.git
cd ejbca-ce
ant build
(works)

```

**Comment by benoiton** [comment]
The problem comes from ant version.
* Ant <1.9.8 calls native2ascii from JDK, which does not exist anymore on JDK >9.
* Ant >=1.9.8 has a builtin native2ascii function, used for JDK >9.

Source: https://ant.apache.org/manual/Tasks/native2ascii.html

For instance EJBCA 8 cannot be build on CentOS 7 with native Ant and JDK 11 packages (alternatives set for java and javac). Using Ant binary from https://ant.apache.org/bindownload.cgi (tarball extracted in /opt, with a symlink to ant binary in /usr/local/bin) makes it work.

**Comment by miguelarman** [comment]
> The problem comes from ant version.
> 
>     * Ant <1.9.8 calls native2ascii from JDK, which does not exist anymore on JDK >9.

This was indeed the problem I was encoutering. My ant version was 1.9.4, and after updating it the issue was fixed.

Thanks a lot for your help @benoiton and @primetomas !
