### ISSUE TITLE
INDEX creation is incompatible with postgresql

### ISSUE THREAD

**Issue by ZnqbuZ** [Keyfactor/ejbca-ce#336]
In postgresql, Line 63 of doc/sql-scripts/create-index-ejbca.sql is causing error like:
`postgres  |  ERROR:  function subjectaltname(integer) does not exist at character 58`
`postgres  |  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.`
`postgres  |  STATEMENT:  CREATE INDEX certificatedata_idx_san ON CertificateData (subjectAltName(750))`
So I'm currently using `CREATE INDEX certificatedata_idx_san ON CertificateData (LEFT(subjectaltname,750));` to create index manually.

**Comment by primetomas** [comment]
This is the same issue as this one: https://github.com/Keyfactor/ejbca-ce/issues/317

Thanks for the working index sample. We will change this for the next release.

**Comment by primetomas** [comment]
Code updated for next release.
