### ISSUE TITLE
EJBCA CE Jboss EAP 7.4 Compatibility 

### ISSUE THREAD

**Issue by karansachdeva24** [Keyfactor/ejbca-ce#35]
Hello,

Could I please check if EJBCA CE is supported on JBOSS EAP 7.4 which has been GA released for almost 10 months now. I tried searching but could not find any documentation around JBOSS EAP 7.4 compatibility

**Comment by kombatminipig** [comment]
Hi, 

Allow me to refer you to the docs: https://doc.primekey.com/ejbca781/ejbca-installation/application-servers/wildfly-22-jboss-eap-7-4

Cheers,
Mike
