### ISSUE TITLE
Script "remove-index-ejbca.sql" fails with PostgreSQL

### ISSUE THREAD

**Issue by benoiton** [Keyfactor/ejbca-ce#350]
SQL script "doc/sql-scripts/remove-index-ejbca.sql" entirely fails with PostgreSQL.

`DROP INDEX <index_name> ON <table_name>` syntax is wrong for [PostgreSQL](https://www.postgresql.org/docs/current/sql-dropindex.html): `ON <table_name>` is not expected.
It does exist with [MariaDB](https://mariadb.com/kb/en/drop-index/) and [MSSQL](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-index-transact-sql?view=sql-server-ver16#syntax).

**Comment by primetomas** [comment]
Added documentation to the top of the script (coming in the next release)
