### ISSUE TITLE
EJBCA + Mysql containers :  Waiting for external database..

### ISSUE THREAD

**Issue by lunitaris** [Keyfactor/ejbca-ce#366]
Hello, 

I am working with containers:
 - DB_container:       a MySQL container, containing a empty Db, ready for EJBCA.
 - EJBCA_container  EJBCA container.

When I start EJBCA, it is waiting for connection to MySQL Db:

```INFO  [/opt/keyfactor/bin/start.sh] (process:1) Waiting for external database 'jdbc:mariadb://127.0.0.1:3306/ejbca?characterEncoding=UTF-8' to become available.```

In order to 'unlock' this, I always need to connect to the Db from my host using mysql-client cmdline:
```
$ mysql -h 127.0.0.1 -P 3306 -u uejbca -p ejbca
Mysql>
```

Then, I quit the MySQL prompt, and I can see in EJBCA container logs, it is unlocked, and EJBCA starts to create the tables for the firt time. 

Is there something to do to fix this?
Seems like I need to initiate a connection to the DB first, so EJBCA can connect to the DB.
If I don't EJBCA is stuck at the state of waiting for external database..

**Comment by primetomas** [comment]
This must be something with the database configuration you use. It is nothing that we have seend.
Check your database logs.

**Comment by lunitaris** [comment]
I had to add &allowPublicKeyRetrieval=true to the JDBC address and it's working now!
