### ISSUE TITLE
Multiple URI for CDP

### ISSUE THREAD

**Issue by mdaur** [Keyfactor/ejbca-ce#394]
Hello,
I just checked out version 8.0.0 and I am asking if it is a bug or a missing feature to support multiple CRL Distribution Point URI's (in Certificate Profiles and CA's). While you can have multiple CA issuer URI's for the AIA it seems not possible to have multiple URI for the CDP's?
/Martin

**Comment by primetomas** [comment]
See here: https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/certificate-profiles-overview/certificate-profile-fields#CertificateProfileFields-CRLDistributionPointsCRL_Distribution_Points
You can separate CDPs by ;
