### ISSUE TITLE
EJBCA WSDL Port mismatch

### ISSUE THREAD

**Issue by MrWildanMD** [Keyfactor/ejbca-ce#402]
When installing ejbca 8.0 using 
OS: RHEL 9
AppServer: WildFly 26 
using standard installation when running it throws wrong port on wsdl (expected: 8443, got: 8080)
where can i change the port?

```xml
<wsdl:service name="EjbcaWSService">
<wsdl:port binding="tns:EjbcaWSServiceSoapBinding" name="EjbcaWSPort">
<soap:address location="https://localhost:8080/ejbca/ejbcaws/ejbcaws"/>
</wsdl:port>
</wsdl:service>
```

**Comment by MrWildanMD** [comment]
@primetomas is this RHEL problem or missconfiguration?
i want to check the documentation but the documentation is currently down

**Comment by primetomas** [comment]
Did you run the installation commands to configure http/wsdl specifics?

/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=webservices:write-attribute(name=wsdl-host, value=jbossws.undefined.host)'
/opt/wildfly/bin/jboss-cli.sh --connect '/subsystem=webservices:write-attribute(name=modify-wsdl-address, value=true)'

**Comment by MrWildanMD** [comment]
Okay, now it's working correctly, many thanks 😄
