### ISSUE TITLE
Documentation Links Don't Work

### ISSUE THREAD

**Issue by ToddBerliner** [Keyfactor/ejbca-ce#406]
https://doc.primekey.com/ejbca/ejbca-installation doesn't open. 

![Screenshot 2023-11-08 at 9 44 03 AM](https://github.com/Keyfactor/ejbca-ce/assets/16885186/5a758f34-a9fd-48fb-98a5-655ba4997d62)

**Comment by nguyenthanhvu240** [comment]
Yes,me too. It have been downed for 2 days and still hasn't been fixed

**Comment by MrWildanMD** [comment]
It's confirmed they still have issues in IT team

**Comment by vacan1t** [comment]
any updates on this?

**Comment by primetomas** [comment]
Soon. 
As a fallback, documentation is also available here. https://download.primekey.com/docs/EJBCA-Enterprise/latest/
