### ISSUE TITLE
Cannot access document

### ISSUE THREAD

**Issue by nguyenthanhvu240** [Keyfactor/ejbca-ce#407]
The website **doc.primekey.com** seems to have been down for 2 days and still hasn't been fixed

**Comment by grindsa** [comment]
![Primegkey](https://github.com/Keyfactor/ejbca-ce/assets/12475288/bbe84bdd-2ff2-4e0d-bea9-f0b087a03f78)

:-(

**Comment by primetomas** [comment]
It's on it's way back up eventually the cert was deliberately allowed to expire during the ongoing IT work.

**Comment by primetomas** [comment]
https://doc.primekey.com/ is up again
