### ISSUE TITLE
Documentation - links don't work

### ISSUE THREAD

**Issue by tomazbracic** [Keyfactor/ejbca-ce#409]
Hi, 

didn't know where else to message you. Can you guys fix the links for documentation, please? 
Wherever I find a link for docs (your site, docker hub) ... none of them works. At this moment, there is no online documentation available, to my knowledge. 

Thanks in advance,
Tomaz B

**Comment by primetomas** [comment]
You can find this issue duscussed here: https://github.com/Keyfactor/ejbca-ce/issues/407
and here: https://github.com/Keyfactor/ejbca-ce/issues/406

A backup link to documentation is here: https://download.primekey.com/docs/EJBCA-Enterprise/latest/EJBCA_8.1_Documentation.html

**Comment by primetomas** [comment]
https://doc.primekey.com/ is up again
