### ISSUE TITLE
Typo error in ScepMessageDispatcherSessionBean.java

### ISSUE THREAD

**Issue by Stueypoo** [Keyfactor/ejbca-ce#418]
Within the file ScepMessageDispatcherSessionBean.java (package org.ejbca.core.protocol.scep) at line 190:
`            log.error(SCEP_RA_MODE_EXTENSION_CLASSNAME + " was found, but could not be instanced. " + e.getMessage());`
is not correct and should be:
`            log.error(SCEP_CLIENT_CERTIFICATE_RENEWAL_CLASSNAME + " was found, but could not be instanced. " + e.getMessage());`

Simple copy and paste error!

**Comment by primetomas** [comment]
Thanks. Fixed this for EJBCA 8.3.0 (8.2 is already tagged). There was also a null-setting above the typo that was copy-paste-error as well.
Internal ticket for reference (not externally visible at the moment, but will be): https://jira.primekey.se/browse/ECA-12013

**Comment by primetomas** [comment]
Would you like to be mentioned on the contributors page? https://www.ejbca.org/contributors/

**Comment by Stueypoo** [comment]
Well done for picking-up on the other error....so easy to make those cut & paste errors!

I don't need a mention on the contributors page for this :-)
