### ISSUE TITLE
RA Web: editing an end-entity and pressing return/enter revokes and deletes it

### ISSUE THREAD

**Issue by uedvt359** [Keyfactor/ejbca-ce#430]
STR:
1. serach for an existing end-entity and press the 'edit' button
2. change something, e.g. set the state to new and set a new enrollment code
3. press return (while in the enrollment code input field)

Expected: the end entity is saved

Actual: the entity is deleted

The problem appears that the default button is "Revoke and delete end entity", which seems rather dangerous.

![image](https://github.com/Keyfactor/ejbca-ce/assets/54625981/d157dee3-edda-4d45-a95e-82d81299b8fa)

Environment:
* EJBCA CE 7.11.0
* Firefox 120

**Comment by primetomas** [comment]
Thanks. A small, but great usability improvement.
