### ISSUE TITLE
[BUG] Cannot create EJBCA instance from Azure Marketplace

### ISSUE THREAD

**Issue by RavilN** [Keyfactor/ejbca-ce#492]
**Describe the Bug**

It is not possible to create instance of the EJBCA SaaS from Azure Marketplace

**To Reproduce**

1. Login to Azure Portlal
2. From Azure Marketplace subscribe to the SaaS **XSmall EJBCA SaaS IoT Deployment with 5000 Certificates Max**
3. When the service creating is initialized, the message appears:
```
Your purchase will be complete once you set up your account on the publisher's website.
Check your email for instructions on setting up your SaaS account.
``` 
4. Wait for the email from Azurer Marketplace with a button in the message body **Confirm Account**
5. Click on the button ``Confirm Account``. It will ask to grant permissions to login using Azure credentials 
6. Provide access as requested.

**Expected Behavior**

It is expected to create an account as the publisher's website and continue with the service initialization.

**Screenshots and Logs**

Instead, an error message appears:

![image](https://github.com/Keyfactor/ejbca-ce/assets/6540681/8bfcc935-ab79-4318-a993-687e458ba0c6)

It is possible to go to the home page. The user name is displayed in the top right corner, and it is possible to log out.

If return to the Azure portal, and click on the button ``Configure Account now``, it redirects to the same page with the same error message.

**Product Deployment** 

Please complete the following information:
 - Deployment format: SaaS 
 - Version unknown

**Desktop**

Please complete the following information:
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Tried with bot Chrome and MS Edge

**Comment by primetomas** [comment]
Hi,
This question is for an Enterprise offering and should probably have been posted to https://www.keyfactor.com/contact-us/, which gives priority. It looks to be something related to the SaaS environment, which the EJBCA Community has no access to.

Having said that, I have alerted the EJBCA SaaS team about this ticket so someone can get in touch with you.

Cheers,
Tomas

**Comment by primetomas** [comment]
Selwyn reports that this issue has been fixed. Thank you very much for reporting it!
