### ISSUE TITLE
[BUG] CA rest api not available

### ISSUE THREAD

**Issue by alex-cbn** [Keyfactor/ejbca-ce#520]
**Describe the Bug**
The /ca/ resource under rest-api is not available. I tried running one of the examples from the documentation to no avail. After further inspection it seems like the entire CA rest api resource is not available.

**To Reproduce**

1. install EBJCA community by following the instructions from the documentation.
2. perform a GET request to https://localhost:8443/ejbca/ejbca-rest-api/v1/ca/status
3. the output is the following json {"error_code":404,"error_message":"RESTEASY003210: Could not find resource for full path: https://localhost:8443/ejbca/ejbca-rest-api/v1/ca/status"}

**Expected Behavior**
See the status of the CA.

**Screenshots and Logs**
These are all the available protocols under system settings
![image](https://github.com/Keyfactor/ejbca-ce/assets/17546807/351c650d-92f9-4b93-8991-7cf9330e442a)

**Product Deployment** 

 - build from sources off github
 - Wildfly 26.0
 - Version 8.0
 - in either deployed on a wildfly docker container or native on Windows 10

**Desktop**

 - OS: Windows 10
 - Browser: Chrome

**Additional Context**

To me it seems like either a mismatch between the documentation and the actual availablilites, or I am doing something wrong during the installation process.

**Comment by svenska-primekey** [comment]
I think it was EJBCA 8.1 CE that added the ca/status endpoint, not 8.0.

**Comment by alex-cbn** [comment]
According to the changelog here, it seems like this is the case with 8.2. Will update and test it in a couple hours, and close the ticket if needed
https://doc.primekey.com/ejbca/ejbca-release-information/ejbca-release-notes/ejbca-community-8-2-release-notes

**Comment by alex-cbn** [comment]
it is indeed. sorry, I was just using the old version
