### ISSUE TITLE
[BUG]Outdated version of the BouncyCastle lib

### ISSUE THREAD

**Issue by kuehne-trustable-de** [Keyfactor/ejbca-ce#537]
**Describe the Bug**

The current version of the ejbca (version 8.2.0.1) uses version 1.75 of BouncyCastle from June 23. All bugs fixed in BC in the meantime are still in present in ejbca. E. g. the OID of Dilithium changed, the ejbca still uses 1.3.6.1.4.1.2.267.7.8.7, which cannot be recognized by the recent version (1.77) of BouncyCastle and other PQC tools.

**To Reproduce**

- unzip the ejbca.ear
- ls lib/bcprov-*
- bcprov-jdk18-on-175.jar is present

**Expected Behavior**

- bcprov-jdk18-on-177.jar or higher is present

**Product Deployment** 

Please complete the following information:
 - Deployment format: software from github
 - Version 8.2.0.1

**Comment by primetomas** [comment]
This is not a bug. The final OID of Dilithium is not defined yet as it will be specified by NIST. There is no need to track changes to Dilithium that closely. On fact the BC 1.75 version is compatible with HSMs (it is Dilithium Round 3) while the BC 1.77 version is not. So Dilithium interoperability will not a thing until after the final specification is out. And the OQS OIDs may still change multiple times until then.

**Comment by primetomas** [comment]
There are no known bugs in BC 1.75 that affects EJBCA.

**Comment by primetomas** [comment]
So you should see it as feature evolution. The next release of EJBCA will include BC 1.77, or 1.78. this will break Dilithium interoperability with some other software, and improve it with some others. Until the final specification of ML-DSA is out and everyone implements that.
