### ISSUE TITLE
Add dependancies check on the project.

### ISSUE THREAD

**Issue by HumanG33k** [Keyfactor/ejbca-ce#545]
Hi,

Last time i check i get some vuln dependancies on ejbca. Not quite or hight level but as it's for a pki soft. 
Maybe a github action/dependabot/renovate/https://github.com/jeremylong/DependencyCheck  or whatever can trigger some regular scan in order to improve "security". 

Maybe some other action related to bom, owasp etc can be setup. No more information as i need to make a closer look to be more precise in my advice. 

thx for the amazing work.

**Comment by primetomas** [comment]
Thanks for the kind words and the suggestions. The dev teams run scans internally, and anlayze impact/relevance of CVEs on dependencies. Currently there is a plan to publicly, in the documentation, publish this analysis. 
I hope this will be a good step for you, and for visibilty/transparency. CVEs in dependencies actually very rarely affect EJBCA (but of course you would prefer to not see it in your scans).

**Comment by primetomas** [comment]
SBOMs are now available from the documentation.
https://docs.keyfactor.com/container/latest/ejbca/ejbca-container-set
