### ISSUE TITLE
Notification Events

### ISSUE THREAD

**Issue by zmmm85** [Keyfactor/ejbca-ce#55]
Hello, we have upgraded EJBCA from 6.5 to 7.8.2.1. We noticed some email notification events are deprecated like STATUSINITIALIZED and STATUSINPROCESS. Is there another way to activate the user notification, like when a user requests a new certificates.

https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/end-entities-overview/end-entity-profiles-overview/e-mail-notifications#EmailNotifications-NotificationEventsNotificationEvents

Thanks in Advanced,
Zm

**Comment by primetomas** [comment]
The INITIALIZED and INPROCESS states were always only internal and not usable for notifications. The other states like NEW and GENERATED are suitable. For example GENERATED would give a notification when a certificate/end-entity has been issued unless "Finish User" has been disabled in the CA settings.

**Comment by zmmm85** [comment]
Thank you @primetomas  for your quick response. 
What about STATUS_WAITINGFORADDAPPROVAL was that also depreciated? because we don't have status code 80 in 7.8.2.1 and we are not sure if that was intentionally or it's a bug in this version. 

For example in EndEntityConstants.java line 88, STATUS_WAITINGFORADDAPPROVAL was added to the STATUS_TEXT_TRANS, but not to STATUS_TEXT in line 96. After we have added STATUS_WAITINGFORADDAPPROVAL  "Status code 80" to STATUS_TEXT , we started to get notification for this event.

https://github.com/Keyfactor/ejbca-ce/blob/main/modules/cesecore-common/src/org/cesecore/certificates/endentity/EndEntityConstants.java

Thanks again,
Zm

**Comment by primetomas** [comment]
It's not deprecated, but as the code says it is used for approvals. 
Perhaps you can describe your use case and what you want to achieve? Are you confgiuring the notification in the end entity profile?
When using approvals you have approvals notifications configuring approvals, and don't need to add notifications in end entity profiles.

PTO Notice: I will be away on vacation July 4-29.

**Comment by zmmm85** [comment]
We are trying to configure ejbca to send notifications to the requester and the admin whenever a user request a new certificate. We are using the End Entity Profile similar to old configuration in our 6.5 version.

Just to confirm, in our case we need to configure approval notification not the end entity so users and admin can get notifications whenever a user request a new certificate?

<img width="671" alt="Screen Shot 2022-07-01 at 11 01 26 AM" src="https://user-images.githubusercontent.com/20634797/176947234-52c088fd-4c0d-45d0-bfe0-d0b22e64c903.png">

Thank you so much for your support,
Zm

**Comment by primetomas** [comment]
Ues, if you are using approvals, you should make sure your approval profiles are configured with appropriate notifications. 
See docs here: https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/approvals

**Comment by zmmm85** [comment]
Thank you @primetomas,
We have configured Approval Profiles and seems everything is working properly.
