### ISSUE TITLE
Docker container outdated

### ISSUE THREAD

**Issue by floriankoenig-work** [Keyfactor/ejbca-ce#576]
The docker container available at https://hub.docker.com/r/keyfactor/ejbca-ce is outdated.
Last container version: [8.2.0.1](https://hub.docker.com/layers/keyfactor/ejbca-ce/8.2.0.1/images/sha256-5a2dd15b2d85a6094ea3cd65444e2b62fcc6afd8a18e9f299f22d71c021b92f5?context=explore)
Last EJBCA Version: 8.2.1 / 8.2.0.3

**Comment by primetomas** [comment]
See https://github.com/Keyfactor/ejbca-ce/discussions/565
