### ISSUE TITLE
[BUG] An exception has occurred when clearing all caches

### ISSUE THREAD

**Issue by chuegel** [Keyfactor/ejbca-ce#578]
**Describe the Bug**

When clearing all caches, EJBCA throws an:
```
An exception has occurred.
KEC cache methods are only supported in EJBCA Enterprise 
```
**To Reproduce**

1. Go to 'System Administration'
2. Click on 'Clear All Caches'
3. See error

**Expected Behavior**

Expected to clear at least caches that can be cleared in CE version

**Product Deployment** 

Please complete the following information:
 - Deployment format:  Helm/Flux
 - Version [8.2.1]

**Desktop**

**Additional Context**

**Comment by primetomas** [comment]
Thanks for the report. I'll take a look in the coming days.

**Comment by primetomas** [comment]
I can reproduce it and will report a regression. The fix didn't make it into the next release 8.3 unfortunately, but I will post the fix here:
in file:
modules/edition-specific/src-interface/org/ejbca/core/protocol/msae/KecCache.java

Remove the line:
        throw new UnsupportedOperationException("KEC cache methods are only supported in EJBCA Enterprise");

in the method flushKecCache()

**Comment by primetomas** [comment]
Internal ticket reference: https://jira.primekey.se/browse/ECA-12425

Closing as fixed, albeit it may take some time before it's pushed.

**Comment by primetomas** [comment]
@chuegel : thank you for the report
