### ISSUE TITLE
[BUG] EJBCA Client Toolbox does not work properly

### ISSUE THREAD

**Issue by aleloco09** [Keyfactor/ejbca-ce#589]
**Describe the Bug**

I was testing EJBCA Client Toolbox in my container (SoftHSM libraries are installed). When i try the `PKCS11HSMKeyTool` I get a fatal error. 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapper (file:/opt/keyfactor/ejbca/dist/clientToolBox/lib/x509-common-util-0.10.9.jar) to method sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String,java.lang.String,sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS,boolean)
WARNING: Please consider reporting this to the maintainers of com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
PKCS11 Token [SunPKCS11-libsofthsm2.so-slot416788204] Password: 
```
Then I enter the password and then *BOOM*:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f74ad437316, pid=2155, tid=2155
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-11.0.21.0.9-1) (11.0.21+9) (build 11.0.21+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-11.0.21.0.9-1) (11.0.21+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0xd316]  __pthread_rwlock_wrlock+0x16
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" (or dumping to /opt/keyfactor/ejbca/dist/clientToolBox/core.2155)
#
# An error report file with more information is saved as:
# /opt/keyfactor/ejbca/dist/clientToolBox/hs_err_pid2155.log
#
# If you would like to submit a bug report, please visit:
#   https://access.redhat.com/support/cases/
#
./ejbcaClientToolBox.sh: line 32:  2155 Aborted                 (core dumped) java ${JAVA_OPT} ${JAVA_OPTS_CTB} -Dlog4j1.compatibility=true -cp "$TOOLBOX_HOME/clientToolBox.jar:${TOOLBOX_HOME}/ext/*" org.ejbca.ui.cli.ClientToolBox "${@}"
```
I tested the tools `PKCS11HSMKeyTool sign`, `verify` and `test` and in both cases I have the same error. Actually, it signs the file and if I verify the signature it is OK. The `test` does not work at all.  

**To Reproduce**

1. Install softhsm on the container
2. Initialise a new token with label `test`
3. In the EJBCA Admin Web create a new PKCS#11 Crypto Token using that slot `test`
4. Create a RSA key, for instance `testKey` (key length 4096)
5. docker exec -it ejbca sh
6. `cd /opt/keyfactor/ejbca/dist/clientToolBox`
7. `echo 'Hello!!!' > mytext.txt`
8. `ejbcaClientToolBox.sh PKCS11HSMKeyTool sign /usr/lib/softhsm/libsofthsm2.so TOKEN_LABEL:test mytext.txt signature.sig testKey -password test`
9. See error (the command also produces two files: `core.<number>` and `hs_err_pid<pid>.log`)
10. The command actualy returns `signature.sig` which is possible to verify using `verify` (the same error will appear though)
11. Possibly try `test` and you will get the same error.

**Product Deployment** 

Please complete the following information:
 - Deployment format: container
 - Version: 8.2.0.1

**Desktop**

Please complete the following information:
 - OS: virtual Machine CentOS 7 (2 CPU cores / 8GB RAM)

**Comment by primetomas** [comment]
You don't say how you have mounted softhsm into the container. I don't think using PKCS11HSMKeyTool inside the container is what you want to do either, so not sure this issue is relevant?

I wrote a bit on the purpose in the other discussion ticket. Sounds like you more want to configure usage of SoftHSM in EJBCA, get a (working) CA configured in EJBCA and run something like "clientToolBox EjbcaWsRaCli stress"?
