### ISSUE TITLE
Update SourceForge release to 8.3.2

### ISSUE THREAD

**Issue by jotamartos** [Keyfactor/ejbca-ce#641]
**Describe the Issue**

Version 8.3.2 is not available in SourceForge

**To Reproduce**

1. You can see version 8.3.2 at https://github.com/Keyfactor/ejbca-ce/releases
2. Go to SourceForge https://sourceforge.net/projects/ejbca/files/ejbca8/
3. Version 8.3.2 is not available there

**Expected Behavior**

Version 8.3.2 available in that platform

**Comment by jotamartos** [comment]
Sorry, it's not a a bug in the application. It's just a download issue

**Comment by primetomas** [comment]
We are moving off sourceforge as a platform. Download from github. We will update the documentation links.

**Comment by jotamartos** [comment]
The problem is that the package you publish in GitHub does not contain all the dependencies, right?

```
➜  /tmp ls -lha ejbca*
-rw-r--r--@ 1 jotamartos  staff    95M Aug  1 15:21 ejbca-ce-r8.3.1.zip #Github
-rw-r--r--@ 1 jotamartos  staff   158M Aug  1 15:25 ejbca_ce_8_3_1.zip #SourceForge
```

**Comment by Realiserad** [comment]
They should be a part of the zip file attached to the release here on GitHub, as dependencies for EJBCA are checked into git (see the `lib` folder).

**Comment by dobicinaitis** [comment]
Dependencies are bundled with GitHub releases. SourceForge downloads were generally larger because they also included an offline version of the [EJBCA documentation site](https://docs.keyfactor.com/ejbca/latest).

```bash
# extract
unzip ejbca-ce-r8.3.1.zip -d github
unzip ejbca_ce_8_3_1.zip -d sourceforge

# compare doc sizes
du -hcs */*/doc

13M github/ejbca-ce-r8.3.1/doc
95M sourceforge/ejbca_ce_8_3_1/doc
```
