### ISSUE TITLE
[BUG] Add entity from CLI - type ignored

### ISSUE THREAD

**Issue by Libeccio84** [Keyfactor/ejbca-ce#666]
As i try to add a new entity with a type different from END-USER I get an enduser anyway.

```
root@master-ca:/opt/ejbca-ce# bin/ejbca.sh ra addendentity
ERROR: Incorrect parameter usage.
    The following mandatory arguments are missing or poorly formed, use --help for more information:
        --username      Username for the new end entity.
        --dn            DN is of form "C=SE, O=MyOrg, OU=MyOrgUnit, CN=MyName" etc.
                        An LDAP escaped DN is for example:
                        DN: CN=Tomas Gustavsson, O=PrimeKey Solutions, C=SE
                        LDAP escaped DN: CN=Tomas Gustavsson\, O=PrimeKey Solutions\, C=SE
        --caname        CA issuing this End Entity.
        --type          Type (mask): INVALID=0; END-USER=1; SENDNOTIFICATION=256; PRINTUSERDATA=512
        --token         Desired token type for the end entity: USERGENERATED, P12, JKS, PEM, BCFKS.

Run command with "--help" to see full manual page.
root@master-ca:/opt/ejbca-ce# bin/ejbca.sh ra addendentity --username fuffa --dn "CN=fuffa" --caname ManagementCA --type 256 --token PEM
Enter password:


Using certificate profile: ENDUSER, with id: 1
Email field cannot be null when send notification type is given.
```

I am running  EJBCA 8.3.2 on Fedora 40 Server. It's a VM running with VMware fusion.

Shall someone help me solving this problem?

**Comment by primetomas** [comment]
Certificate profile is not the same thing as end entity type. The ENDUSER certificate profile is just the default profile since you didn’t specify a certificate profile option.

**Comment by Libeccio84** [comment]
Many thanks for your fast reply :)
From your answer it looks like it is possible to specify a certificate profile even via CLI, bit I cannot see it among available options: how can I do that?

Thanks in advance!

**Comment by Libeccio84** [comment]
Many thanks for your fast reply. As stated from `bin/ejbca.sh ra addendentity --help` I have seen that specifying the `--certprofile` option I get what I was looking for.
