### ISSUE TITLE
docker - cgroup file not found 

### ISSUE THREAD

**Issue by tmihajloski** [Keyfactor/ejbca-ce#670]
Hi,

I am experiencing a similar issue to https://github.com/Keyfactor/ejbca-ce/issues/240 where the container fails to start because the startup script cannot find the cgroup file. I am trying to run the container on a QNAP NAS inside their Container Station app as a docker container. 

Here is the output during the container startup:

`2024-09-24 02:29:22,322+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Configure logging for Application Server
2024-09-24 02:29:22,384+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Configure logging for ejbca
2024-09-24 02:29:22,449+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) uid=10001 gid=0(root) groups=0(root)
2024-09-24 02:29:22,841+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Detected 4.0 available core(s).
2024-09-24 02:29:22,856+0000 ERROR [/opt/keyfactor/bin/start.sh] (process:1) Expected cgroup file not found. Aborting startup.`

I am using keyfactor/ejbca-ce:latest to create the container

The QNAP is TS-253D version 5.2.0.2860
The docker version running on the QNAP is 20.10.27-qnap1

Thanks!

**Comment by primetomas** [comment]
The cgroup patch from #240 is in there. What does cgroups look like in QNAP?

**Comment by svenska-primekey** [comment]
> The cgroup patch from #240 is in there. What does cgroups look like in QNAP?

Also you should check if the QNAP supports cgroups.

**Comment by tmihajloski** [comment]
This is the contents of the cgroup inside the container:

drwxr-xr-x 2 root root 0 Sep 27 14:58 blkio
drwxr-xr-x 2 root root 0 Sep 27 14:58 cgroups_antivirus
drwxr-xr-x 2 root root 0 Sep 27 14:58 cpu
drwxr-xr-x 2 root root 0 Sep 27 14:58 cpuacct
drwxr-xr-x 2 root root 0 Sep 27 14:58 cpuset
drwxr-xr-x 2 root root 0 Sep 27 14:58 devices
drwxr-xr-x 2 root root 0 Sep 27 14:58 freezer
drwxr-xr-x 2 root root 0 Sep 27 14:58 pids
drwxr-xr-x 2 root root 0 Sep 27 14:58 systemd


It doesn't have the memory folder.

**Comment by primetomas** [comment]
Can you ask QNAP about that, why there is no memory?

**Comment by Realiserad** [comment]
The memory calculation for the JVM running EJBCA is done in the `start.sh` script by manually inspecting files in `cgroupfs`. It cannot gobble up all resources detected ([the default behaviour](https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#recent_changes_in_openjdk_s_container_awareness_code)) as there may be other processes running inside the container.

The following files must be readable at container boot:

- `/sys/fs/cgroup/cpu/cpu.cfs_period_us` and `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` or `/proc/cpuinfo`
- `/sys/fs/cgroup/memory/memory.limit_in_bytes` or `/sys/fs/cgroup/memory.max`

This article

**Comment by tmihajloski** [comment]
I opened a ticket with QNAP, they are investigating, but looks like issue on the NAS side not ejbca.

**Comment by primetomas** [comment]
Great. Let us know the outcome.
