### ISSUE TITLE
Change the SCEP responder challenge value.

### ISSUE THREAD

**Issue by bergstiefelbene** [Keyfactor/ejbca-ce#690]
Hi,
we have an issue if a lot of INTUNE managed devices were requesting a renew of certificates that the challenge time is to short because INTUNE is handling that to slow. 

Error:
caused by: org.cesecore.azure.AzureException: Error validating SCEP request: ChallengeExpired:SCEP challenge has expired.SCEP Challenge has expired. challengeExpInterval=60, challengeExpiration=10/21/2024 09:55:33, challengeCreation=10/21/2024 08:55:33
        at deployment.ejbca.ear//org.cesecore.azure.IntuneRestApi.validateRequest(IntuneRestApi.java:442)

I do not see any possibilty to change that to 300sec or so to give more time in our EJBCA CA marketplace AzureSaas solution.
What can I do to solve that?

**Comment by primetomas** [comment]
This looks like an EJBCA Enterprise support question, is it?
