### ISSUE TITLE
Need Support on 3GPP CMP Operations

### ISSUE THREAD

**Issue by eamkhal** [Keyfactor/ejbca-ce#751]
Hi, 

We have an o-RAN radio product which has one vendor certificate from third party CA server and has a private key.
We are using EJBCA 8.3.2 community and I am not able to find below option:
![image](https://github.com/user-attachments/assets/ab387e20-f951-4d1d-b5a6-f0c7650c17cb)

Also, how can I make autorequest from o-RU using CMP?
 
Thank you!

//Khalid

**Comment by mike-agrenius-kushner** [comment]
Hi Khalid,

3GPP is an Enterprise feature, so to get access to it you're going to have to contact Sales at Keyfactor.

Cheers,
Mike
