### ISSUE TITLE
URLs in [?]-buttons do not work with confluence-based documentation

### ISSUE THREAD

**Issue by uedvt359** [Keyfactor/ejbca-ce#81]
**Summary**:
- during the migration to confluence docs, the paths to subpages changed, and this has not been updated in the `[?]` buttons in the web-UI.

**Environment**:
- EJBCA-CE 7.9.0.2
- WildFly 24.0.1.Final
- RHEL 8.6 x86_64

**Details**:

As a workaround for issue #80, we tried to change `web.docbaseuri` in the `web.properties` file from `internal` to the URL of the online documentation. 

After a rebuild, the links to documentation in the web UI now point there, but the direct links are still broken: For example, clicking on the `[?]` at adminweb/home -> CA Status links to `https://doc.primekey.com/ejbca790/doc/CA_Operations_Guide.html#CA%20Status`, but this page does not exist in the online documentation (and neither do any other pages that are linked to in the ?-buttons). 

It should be `https://doc.primekey.com/ejbca790/ejbca-operations/ejbca-operations-guide/ca-operations-guide/ejbca-overview-page#EJBCAOverviewPage-CAStatus`. (I checked this by manually searching through the documentation)

All documentation paths should probably be updated to reflect their new URLs.

**Comment by primetomas** [comment]
Thanks for the report. It's a bit tricky now since the documentation built into the zip release as sf.net does have the URLs and anchors.
https://sourceforge.net/projects/ejbca/files/ejbca7/

I created this issue: https://jira.primekey.se/browse/ECA-10907

**Comment by uedvt359** [comment]
With this zip from SF, the documentation paths are better, but still not 100% correct. Using the same example as above: the ? next to `CA Status` on /ejbca/adminweb/ links to `/ejbca/doc/CA_Operations_Guide.html#CA%20Status`. This page exists now (yay), but the documentation for lives at a subpage of the Operations Guide, at `/ejbca/doc/EJBCA_Overview_Page.html`. This would still require changing the URLs in the `[?]` buttons.

Also, the anchor is now `#src-108529490_id-.EJBCAOverviewPagev7.5.0-CAStatus`, so even if the URL were correct, it would not jump to the correct position. I guess that is just how the confluence export works; maybe they could be massaged after the export into something stable.

Again, thanks: This is already way better, now that we know how to get the local documentation at all. It seems, the paths in the online documentation are just different and incompatible. I would suggest removing the default external URL from the web.properties.sample file, to avoid confusion.

**Comment by primetomas** [comment]
Thanks for the suggestion, we'll track it and try to figure out a good way in the future. 

The anchors where changed when moving to confluence, which allowed the documentation to be much better, but not as good support for anchors...it's something we are aware one but hasn't been trivial to fix, and not highest priority unfortunately.

**Comment by primetomas** [comment]
Closing this issue for now, it's a known registered issue with the team now. No immediate roadmap scheduled for this though, sorry.
