### ISSUE TITLE
RA Web Role Members "Unknown CA"

### ISSUE THREAD

**Issue by rmuehl** [Keyfactor/ejbca-ce#84]
ejbca-ce-EJBCA_7_9_0_2_20220616

When adding a Role Member via RA Web it results in an "Unknown CA".

Doing this in the Administration Web GUI its doing well, and is also shown correctly in RA Web.

**Comment by rmuehl** [comment]
The same happens, when editing an existing Member in RA Web.

**Comment by primetomas** [comment]
This was fixed recently and the will be available in the next release (not too far away).
https://jira.primekey.se/browse/ECA-10502
