### ISSUE TITLE
Problem with command: "ant runinstall" when use Orcale Database (Ejbca community version 7.9.0.2)

### ISSUE THREAD

**Issue by tuantavsc** [Keyfactor/ejbca-ce#92]
Is it bug in Ejbca community version 7.9.0.2?
I can run command: "ant runinstall" successfully when using MySQL database BUT when I try to use Orcale Database, it throw exception like this:
![image](https://user-images.githubusercontent.com/104489887/187340503-09c24717-7370-40be-b529-b645a7460f69.png)
Wifldly:
![image](https://user-images.githubusercontent.com/104489887/187340544-0ce0cd80-0745-41e7-9824-5e9583c1c565.png)
I am using Orcale Database 21c.

**Comment by mike-agrenius-kushner** [comment]
Hi,

Not sure, but we have plenty of customers running Oracle on the EE-side. 

Question: Have you set the driver for Oracle correctly in the configuration, or are you still on the mysql-driver?

Cheers,
Mike

**Comment by tuantavsc** [comment]
Hi,
I have set driver for Oracle successfully! This is list drivers:
![image](https://user-images.githubusercontent.com/104489887/187374119-73aa63b0-aebb-4093-9e85-66874fe2f6ad.png)
This is my configuration:
![image](https://user-images.githubusercontent.com/104489887/187374226-d372660a-b6e8-4624-afb0-2cbd904ddd51.png)

**Comment by mike-agrenius-kushner** [comment]
Huh, weirdness. The error is happening in Wildfly though, so fairly sure it's not a bug in EJBCA itself. 

What happens if you manually remove the mysql-driver in the jboss CLI? I'm thinking that maybe it's being rubbish and defaulting to the first one it finds. 

What do you get if you start Wildfly but without the ejbca.ear deployed (i.e. just delete the EAR and restart Wildfly)?

Cheers,
Mike

**Comment by tuantavsc** [comment]
Hi,
This is log when I start Wildfly without ejbca..ear.
https://drive.google.com/file/d/12wYcrI5hNhEusngU8BAnZpHOiDY6ir_9/view?usp=sharing
This is list drivers after remove other drivers:
![image](https://user-images.githubusercontent.com/104489887/187376517-3caae22f-d7c1-480d-a5fb-54419bf24ac2.png)

**Comment by tuantavsc** [comment]
The error appear when I run command: "ant runinstall", it mean, it deploy successfully!

**Comment by tuantavsc** [comment]
Hello,
I am using WF 14
![image](https://user-images.githubusercontent.com/104489887/187382934-60beeddb-6e96-45a9-8e9f-8c6d1168d0cc.png)
Yes, I am stuck in the step Installing!
https://download.primekey.com/docs/EJBCA-Enterprise/7_4_3_3/Installing_EJBCA_as_a_CA_with_a_Management_CA.html

**Comment by tuantavsc** [comment]
This is log when I run command line: "ant runinstall".
Hope it can help find the issue.
https://drive.google.com/file/d/1h1_uGDs7CCGNb_4b6E_BHl3vWT4ZQ98u/view?usp=sharing

**Comment by tuantavsc** [comment]
I see the exception is throw from this code:
Caused by: Error : 933, Position : 240, Sql = select max(crldata0_.cRLNumber) as col_0_0_ from CRLData crldata0_ where crldata0_.issuerDN=:1  and crldata0_.deltaCRLIndicator=-1 and (crldata0_.crlPartitionIndex=-1 or crldata0_.crlPartitionIndex=0 or crldata0_.crlPartitionIndex is null) limit :2 , OriginalSql = select max(crldata0_.cRLNumber) as col_0_0_ from CRLData crldata0_ where crldata0_.issuerDN=? and crldata0_.deltaCRLIndicator=-1 and (crldata0_.crlPartitionIndex=-1 or crldata0_.crlPartitionIndex=0 or crldata0_.crlPartitionIndex is null) limit ?, Error Msg = ORA-00933: SQL command not properly ended

**Comment by mike-agrenius-kushner** [comment]
Huh, are you sure about being in WF14? Looking at the logs in your first post appserver.home is set to WF9? Did you change since then? 

Thanks for the full log – the exception seems to be thrown from within the Oracle driver, so hence why I believe it's a compatibility issue. 

Also, we haven't performed any CI testing on Oracle 21, so I can't guarantee we are compatible with that. I'd highly recommend you change to Oracle 19, and use the JDK8 driver from [here](https://download.oracle.com/otn-pub/otn_software/jdbc/1916/ojdbc8.jar).

Cheers,
Mike

**Comment by primetomas** [comment]
Are you sure you set Oracle as the database type in conf/database.properties and then ran "ant clean build deployear"?

**Comment by tuantavsc** [comment]
> 

Thank @mike-agrenius-kushner,
Yes, I have updated WF14.
I will try to use Oracle 19. Will let me know when done.

**Comment by tuantavsc** [comment]
> Are you sure you set Oracle as the database type in conf/database.properties and then ran "ant clean build deployear"?

Yes, I have setted!

**Comment by tuantavsc** [comment]
> Huh, are you sure about being in WF14? Looking at the logs in your first post appserver.home is set to WF9? Did you change since then?
> 
> Thanks for the full log – the exception seems to be thrown from within the Oracle driver, so hence why I believe it's a compatibility issue.
> 
> Also, we haven't performed any CI testing on Oracle 21, so I can't guarantee we are compatible with that. I'd highly recommend you change to Oracle 19, and use the JDK8 driver from [here](https://download.oracle.com/otn-pub/otn_software/jdbc/1916/ojdbc8.jar).
> 
> Cheers, Mike

Hi @mike-agrenius-kushner @primetomas,
I have installed Ejbca successfully with Orcale 19c.
If you have time, please check the issue in Orcale 21c.
Thank you!
